#!/bin/bash
# Setup Git Worktrees for Expensify App
# Run: bash scripts/setup-worktrees.sh
# Or ask Claude: /setup-worktrees
#
# Idempotent - safe to run multiple times.
# Creates 3 general worktrees + shell aliases. Main repo = main worktree.

set -euo pipefail

# --- Configuration ---
NUM_WORKTREES=3
ALIAS_FILE="$HOME/.config/worktree-aliases.zsh"

# --- Detect repo root ---
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_PARENT="$(dirname "$REPO_ROOT")"
REPO_NAME="$(basename "$REPO_ROOT")"
WORKTREE_DIR="$REPO_PARENT/${REPO_NAME}-worktrees"

echo "=== Expensify App Worktree Setup ==="
echo ""
echo "Repo root:     $REPO_ROOT"
echo "Worktree dir:  $WORKTREE_DIR"
echo "Alias file:    $ALIAS_FILE"
echo ""

# --- Ensure we're in a git repo ---
if ! git -C "$REPO_ROOT" rev-parse --is-inside-work-tree &>/dev/null; then
    echo "ERROR: $REPO_ROOT is not a git repository"
    exit 1
fi

# --- Fetch latest main ---
echo "Fetching latest from origin..."
git -C "$REPO_ROOT" fetch origin main --quiet 2>/dev/null || true

# --- Create worktree directory ---
mkdir -p "$WORKTREE_DIR"

# --- Create general worktrees (w1..wN) ---
for i in $(seq 1 "$NUM_WORKTREES"); do
    WT_PATH="$WORKTREE_DIR/w${i}"
    BRANCH_NAME="wt/w${i}"

    if [ -d "$WT_PATH" ]; then
        echo "  [exists] w${i} -> $WT_PATH"
    else
        echo "  [create] w${i} -> $WT_PATH"
        # Create the placeholder branch if it doesn't exist
        if ! git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/${BRANCH_NAME}" 2>/dev/null; then
            git -C "$REPO_ROOT" branch "$BRANCH_NAME" main 2>/dev/null || true
        fi
        git -C "$REPO_ROOT" worktree add "$WT_PATH" "$BRANCH_NAME" 2>/dev/null || {
            echo "    WARNING: Could not create worktree w${i}, skipping"
        }
    fi
done

echo ""

# --- Create alias file ---
mkdir -p "$(dirname "$ALIAS_FILE")"

if [ -f "$ALIAS_FILE" ]; then
    echo "Alias file already exists at $ALIAS_FILE"
    echo "  To regenerate, delete it first: rm $ALIAS_FILE"
else
    echo "Creating alias file at $ALIAS_FILE..."

    cat > "$ALIAS_FILE" << 'ALIASES_EOF'
#!/bin/zsh
# Git Worktree Aliases for Expensify App
# Source this in your ~/.zshrc: source ~/.config/worktree-aliases.zsh
# Generated by scripts/setup-worktrees.sh

# --- Auto-detect paths ---
# Override these if your repo is in a non-standard location
: "${WT_REPO_ROOT:=$HOME/Developer/App}"
: "${WT_WORKTREE_DIR:=$HOME/Developer/App-worktrees}"

# === Quick Navigation ===
alias w1="cd $WT_WORKTREE_DIR/w1"
alias w2="cd $WT_WORKTREE_DIR/w2"
alias w3="cd $WT_WORKTREE_DIR/w3"
alias main="cd $WT_REPO_ROOT"

# === Claude Launchers ===
alias c1="cd $WT_WORKTREE_DIR/w1 && claude"
alias c2="cd $WT_WORKTREE_DIR/w2 && claude"
alias c3="cd $WT_WORKTREE_DIR/w3 && claude"
alias cmain="cd $WT_REPO_ROOT && claude"

# === Git Worktree Management ===
alias wl='git worktree list'
alias wp='git worktree prune'

# === Helper Functions ===

# Show which worktree you're currently in
wwhich() {
  local current_dir="$(pwd)"
  if [[ "$current_dir" == *"/App-worktrees/w1"* ]]; then
    echo "w1 (worktree 1)"
  elif [[ "$current_dir" == *"/App-worktrees/w2"* ]]; then
    echo "w2 (worktree 2)"
  elif [[ "$current_dir" == *"/App-worktrees/w3"* ]]; then
    echo "w3 (worktree 3)"
  elif [[ "$current_dir" == *"${WT_REPO_ROOT##*/}" ]]; then
    echo "main (primary worktree)"
  else
    echo "Unknown worktree or not in a worktree"
  fi
  local branch=$(git branch --show-current 2>/dev/null)
  if [ -n "$branch" ]; then
    echo "Branch: $branch"
  fi
}

# Quick branch checkout in current worktree
wco() {
  if [ -z "$1" ]; then
    echo "Usage: wco <branch-name>"
    return 1
  fi
  git checkout "$1"
}

# Create new branch in current worktree from main
wnew() {
  if [ -z "$1" ]; then
    echo "Usage: wnew <branch-name>"
    return 1
  fi
  git checkout -b "$1" main
}

# Pull latest main in current worktree
wpull() {
  local current_branch=$(git branch --show-current)
  git checkout main
  git pull origin main
  if [ "$current_branch" != "main" ]; then
    git checkout "$current_branch"
  fi
}

# Show status of all worktrees
wstatus() {
  echo "=== All Worktrees Status ==="
  git worktree list
  echo ""
  echo "=== Git Status ==="
  git status --short
}

# Open current worktree in VS Code
wcode() {
  code .
}

# Install npm dependencies in current worktree
wnpm() {
  echo "Installing npm dependencies in current worktree..."
  npm install
}

# Quick PR checkout in a worktree
wpr() {
  if [ -z "$1" ]; then
    echo "Usage: wpr <pr-number> [worktree]"
    echo "Example: wpr 12345      (uses w1)"
    echo "Example: wpr 12345 w2   (uses w2)"
    return 1
  fi
  local wt="${2:-w1}"
  cd "$WT_WORKTREE_DIR/$wt"
  git checkout main
  git pull origin main
  gh pr checkout "$1"
  echo ""
  echo "PR #$1 checked out in $wt"
}

# Show help for worktree commands
whelp() {
  echo "=== Worktree Quick Reference ==="
  echo ""
  echo "Navigation:"
  echo "  w1, w2, w3  - Jump to worktrees 1-3"
  echo "  main        - Jump to main worktree"
  echo ""
  echo "Claude Launchers:"
  echo "  c1, c2, c3  - Open Claude in worktrees 1-3"
  echo "  cmain       - Open Claude in main worktree"
  echo ""
  echo "Worktree Info:"
  echo "  wwhich            - Show which worktree you're in"
  echo "  wl                - List all worktrees"
  echo "  wstatus           - Show status of all worktrees"
  echo ""
  echo "Branch Operations:"
  echo "  wco <branch>      - Checkout existing branch"
  echo "  wnew <branch>     - Create new branch from main"
  echo "  wpull             - Pull latest main"
  echo ""
  echo "PR Review:"
  echo "  wpr <number> [wt] - Checkout PR in worktree (default: w1)"
  echo ""
  echo "Utilities:"
  echo "  wnpm              - Install npm dependencies"
  echo "  wcode             - Open current worktree in VS Code"
  echo "  whelp             - Show this help"
}
ALIASES_EOF

    echo "  Done."
fi

echo ""

# --- Source from shell RC file ---
SHELL_RC="$HOME/.zshrc"
SOURCE_LINE="source $ALIAS_FILE"

# Also check for variants with quotes or different spacing
if grep -qF "worktree-aliases.zsh" "$SHELL_RC" 2>/dev/null; then
    echo "Shell RC already sources the alias file."
else
    echo "Adding source line to $SHELL_RC..."
    echo "" >> "$SHELL_RC"
    echo "# Git worktree aliases for Expensify App" >> "$SHELL_RC"
    echo "$SOURCE_LINE" >> "$SHELL_RC"
    echo "  Done."
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Worktrees created:"
git -C "$REPO_ROOT" worktree list
echo ""
echo "To activate aliases in your current shell:"
echo "  source $ALIAS_FILE"
echo ""
echo "Type 'whelp' for the full command reference."
