// Auto-generated SVG assets file
// Generated by: npx ts-node scripts/listFiles.ts --type svg --prepareSvgArray
// Total SVG files: 605

import HomeBackgroundIos1 from '@assets/images/home-background--ios.svg';
import HomeBackgroundDesktop2 from '@assets/images/home-background--desktop.svg';
import HomeBackgroundMobile3 from '@assets/images/home-background--mobile.svg';
import HomeBackgroundAndroid4 from '@assets/images/home-background--android.svg';
import Lounge5 from '@assets/images/product-illustrations/lounge.svg';
import OlddotWireframe6 from '@assets/images/olddot-wireframe.svg';
import EreceiptBackground7 from '@assets/images/eReceipt_background.svg';
import TestDrive8 from '@assets/images/test-drive.svg';
import IllustrationCardReplacementSuccess9 from '@assets/images/product-illustrations/illustration__card-replacement-success.svg';
import SimpleIllustrationEmptyShelves10 from '@assets/images/simple-illustrations/simple-illustration__empty-shelves.svg';
import EmptystateExpensifycard11 from '@assets/images/emptystate__expensifycard.svg';
import EmptystateHoldexpense12 from '@assets/images/product-illustrations/emptystate__holdexpense.svg';
import EreceiptBgimage13 from '@assets/images/eReceipt-BGImage.svg';
import EreceiptbgTangerine14 from '@assets/images/eReceiptBGs/eReceiptBG_tangerine.svg';
import EreceiptbgPink15 from '@assets/images/eReceiptBGs/eReceiptBG_pink.svg';
import ToddInCar16 from '@assets/images/product-illustrations/todd-in-car.svg';
import ToddWithPhones17 from '@assets/images/product-illustrations/todd-with-phones.svg';
import EreceiptbgYellow18 from '@assets/images/eReceiptBGs/eReceiptBG_yellow.svg';
import MagicCode19 from '@assets/images/product-illustrations/magic-code.svg';
import EmptystateCardPos20 from '@assets/images/companyCards/emptystate__card-pos.svg';
import EreceiptbgIce21 from '@assets/images/eReceiptBGs/eReceiptBG_ice.svg';
import Abracadabra22 from '@assets/images/product-illustrations/abracadabra.svg';
import EreceiptbgGreen23 from '@assets/images/eReceiptBGs/eReceiptBG_green.svg';
import EmptystateTravel24 from '@assets/images/product-illustrations/emptystate__travel.svg';
import EmptystateReceiptfairy25 from '@assets/images/product-illustrations/emptystate__receiptfairy.svg';
import EreceiptbgBlue26 from '@assets/images/eReceiptBGs/eReceiptBG_blue.svg';
import HomeIllustrationHands27 from '@assets/images/product-illustrations/home-illustration-hands.svg';
import LaptopWithSecondScreenX28 from '@assets/images/laptop-with-second-screen-x.svg';
import Cardillustration29 from '@assets/images/expensifyCard/cardIllustration.svg';
import MagnifyingGlassSpyMouthClosed30 from '@assets/images/magnifying-glass-spy-mouth-closed.svg';
import SpreadsheetComputer31 from '@assets/images/spreadsheet-computer.svg';
import PaymentHands32 from '@assets/images/product-illustrations/payment-hands.svg';
import EducationalIllustrationMultiScan33 from '@assets/images/educational-illustration__multi-scan.svg';
import EmptystateBigVault34 from '@assets/images/simple-illustrations/emptystate__big-vault.svg';
import LaptopWithSecondScreenAndHourglass35 from '@assets/images/laptop-with-second-screen-and-hourglass.svg';
import PendingBank36 from '@assets/images/companyCards/pending-bank.svg';
import ConnectionComplete37 from '@assets/images/connection-complete.svg';
import RocketDude38 from '@assets/images/product-illustrations/rocket-dude.svg';
import MoneyStack39 from '@assets/images/money-stack.svg';
import LaptopWithSecondScreenSync40 from '@assets/images/laptop-with-second-screen-sync.svg';
import Computer41 from '@assets/images/computer.svg';
import PendingstateLaptopWithHourglassAndCards42 from '@assets/images/companyCards/pendingstate_laptop-with-hourglass-and-cards.svg';
import RunningTurtle43 from '@assets/images/running-turtle.svg';
import SimpleIllustrationBigrocket44 from '@assets/images/simple-illustrations/simple-illustration__bigrocket.svg';
import SimpleIllustrationGears45 from '@assets/images/simple-illustrations/simple-illustration__gears.svg';
import MoneyWaving46 from '@assets/images/money-waving.svg';
import SimpleIllustrationHotdogstand47 from '@assets/images/simple-illustrations/simple-illustration__hotdogstand.svg';
import RocketBlue48 from '@assets/images/product-illustrations/rocket--blue.svg';
import Hand49 from '@assets/images/hand.svg';
import Suntrust50 from '@assets/images/cardicons/suntrust.svg';
import DefaultAvatar1651 from '@assets/images/avatars/user/default-avatar_16.svg';
import ThreeLeggedLaptopWoman52 from '@assets/images/product-illustrations/three_legged_laptop_woman.svg';
import DefaultAvatar2453 from '@assets/images/avatars/user/default-avatar_24.svg';
import Suntrust54 from '@assets/images/bank-icons/suntrust.svg';
import DefaultAvatar355 from '@assets/images/avatars/user/default-avatar_3.svg';
import AdvancedApprovalsIconSquare56 from '@assets/images/simple-illustrations/advanced-approvals-icon-square.svg';
import SimpleIllustrationPiggybank57 from '@assets/images/simple-illustrations/simple-illustration__piggybank.svg';
import DefaultAvatar458 from '@assets/images/avatars/user/default-avatar_4.svg';
import EmptystateExpenses59 from '@assets/images/product-illustrations/emptystate__expenses.svg';
import SimpleIllustrationReceiptLocationMarker60 from '@assets/images/simple-illustrations/simple-illustration__receipt-location-marker.svg';
import DefaultAvatar761 from '@assets/images/avatars/user/default-avatar_7.svg';
import MushroomTopHat62 from '@assets/images/product-illustrations/mushroom-top-hat.svg';
import DefaultAvatar1363 from '@assets/images/avatars/user/default-avatar_13.svg';
import DefaultAvatar1464 from '@assets/images/avatars/user/default-avatar_14.svg';
import DefaultAvatar2265 from '@assets/images/avatars/user/default-avatar_22.svg';
import Uber66 from '@assets/images/integrationicons/uber.svg';
import DefaultAvatar2367 from '@assets/images/avatars/user/default-avatar_23.svg';
import DefaultAvatar568 from '@assets/images/avatars/user/default-avatar_5.svg';
import DefaultAvatar2069 from '@assets/images/avatars/user/default-avatar_20.svg';
import SimpleIllustrationWorkflows70 from '@assets/images/simple-illustrations/simple-illustration__workflows.svg';
import SimpleIllustrationFilters71 from '@assets/images/simple-illustrations/simple-illustration__filters.svg';
import DefaultAvatar672 from '@assets/images/avatars/user/default-avatar_6.svg';
import DefaultAvatar1573 from '@assets/images/avatars/user/default-avatar_15.svg';
import DefaultAvatar1074 from '@assets/images/avatars/user/default-avatar_10.svg';
import DefaultAvatar875 from '@assets/images/avatars/user/default-avatar_8.svg';
import SimpleIllustrationOpensafe76 from '@assets/images/simple-illustrations/simple-illustration__opensafe.svg';
import DefaultAvatar177 from '@assets/images/avatars/user/default-avatar_1.svg';
import DefaultAvatar1978 from '@assets/images/avatars/user/default-avatar_19.svg';
import EmptystateSpyPigeon79 from '@assets/images/emptystate__spy-pigeon.svg';
import DefaultAvatar2180 from '@assets/images/avatars/user/default-avatar_21.svg';
import DefaultAvatar1181 from '@assets/images/avatars/user/default-avatar_11.svg';
import DefaultAvatar1782 from '@assets/images/avatars/user/default-avatar_17.svg';
import ReceiptsStackedOnPin83 from '@assets/images/product-illustrations/receipts-stacked-on-pin.svg';
import SimpleIllustrationSmallrocket84 from '@assets/images/simple-illustrations/simple-illustration__smallrocket.svg';
import Safe85 from '@assets/images/product-illustrations/safe.svg';
import CardExpensify86 from '@assets/images/companyCards/card-expensify.svg';
import ReceiptUpload87 from '@assets/images/receipt-upload.svg';
import SubscriptionDetailsApprovedlogo88 from '@assets/images/subscription-details__approvedlogo.svg';
import DefaultAvatar1289 from '@assets/images/avatars/user/default-avatar_12.svg';
import SubscriptionDetailsApprovedlogoLight90 from '@assets/images/subscription-details__approvedlogo--light.svg';
import SimpleIllustrationReceiptWrangler91 from '@assets/images/simple-illustrations/simple-illustration__receipt-wrangler.svg';
import NavyFederalCreditUnion92 from '@assets/images/cardicons/navy-federal-credit-union.svg';
import EmptystatePuzzlepieces93 from '@assets/images/simple-illustrations/emptystate__puzzlepieces.svg';
import TurtleInShell94 from '@assets/images/turtle-in-shell.svg';
import SimpleIllustrationMoneywings95 from '@assets/images/simple-illustrations/simple-illustration__moneywings.svg';
import DefaultAvatar1896 from '@assets/images/avatars/user/default-avatar_18.svg';
import SimpleIllustrationAccounting97 from '@assets/images/simple-illustrations/simple-illustration__accounting.svg';
import CardExpensifyLarge98 from '@assets/images/companyCards/large/card-expensify-large.svg';
import SimpleIllustrationMoneyReceipts99 from '@assets/images/simple-illustrations/simple-illustration__money-receipts.svg';
import SimpleIllustrationMessageinabottle100 from '@assets/images/simple-illustrations/simple-illustration__messageinabottle.svg';
import SimpleIllustrationBankArrow101 from '@assets/images/simple-illustrations/simple-illustration__bank-arrow.svg';
import SimpleIllustrationEmptyState102 from '@assets/images/simple-illustrations/simple-illustration__empty-state.svg';
import SimpleIllustrationSubscriptionAnnual103 from '@assets/images/simple-illustrations/simple-illustration__subscription-annual.svg';
import SimpleIllustrationPerdiem104 from '@assets/images/simple-illustrations/simple-illustration__perdiem.svg';
import SimpleIllustrationPillow105 from '@assets/images/simple-illustrations/simple-illustration__pillow.svg';
import BrokenMagnifyingGlass106 from '@assets/images/product-illustrations/broken-magnifying-glass.svg';
import ExpensifyCardDark107 from '@assets/images/cardicons/expensify-card-dark.svg';
import CharlesSchwab108 from '@assets/images/cardicons/charles-schwab.svg';
import RocketOrange109 from '@assets/images/product-illustrations/rocket--orange.svg';
import SimpleIllustrationEncryption110 from '@assets/images/simple-illustrations/simple-illustration__encryption.svg';
import DefaultAvatar2111 from '@assets/images/avatars/user/default-avatar_2.svg';
import FolderWithPapers112 from '@assets/images/product-illustrations/folder-with-papers.svg';
import Visa113 from '@assets/images/companyCards/visa.svg';
import SimpleIllustrationEnvelopereceipt114 from '@assets/images/simple-illustrations/simple-illustration__envelopereceipt.svg';
import DefaultAvatar9115 from '@assets/images/avatars/user/default-avatar_9.svg';
import CardVisa116 from '@assets/images/companyCards/card-visa.svg';
import NavyFederalCreditUnion117 from '@assets/images/bank-icons/navy-federal-credit-union.svg';
import SimpleIllustrationThumbsupstars118 from '@assets/images/simple-illustrations/simple-illustration__thumbsupstars.svg';
import SimpleIllustrationRealtimereports119 from '@assets/images/simple-illustrations/simple-illustration__realtimereports.svg';
import ExpensifyCard120 from '@assets/images/expensify-card.svg';
import SimpleIllustrationMoneyintowallet121 from '@assets/images/simple-illustrations/simple-illustration__moneyintowallet.svg';
import SimpleIllustrationReplaceReceipt122 from '@assets/images/simple-illustrations/simple-illustration__replace-receipt.svg';
import CardWellsfargo123 from '@assets/images/companyCards/card-wellsfargo.svg';
import CapitalOne124 from '@assets/images/cardicons/capital-one.svg';
import SimpleIllustrationTrackShoe125 from '@assets/images/simple-illustrations/simple-illustration__track-shoe.svg';
import Telescope126 from '@assets/images/product-illustrations/telescope.svg';
import SimpleIllustrationPaperairplane127 from '@assets/images/simple-illustrations/simple-illustration__paperairplane.svg';
import CardVisaLarge128 from '@assets/images/companyCards/large/card-visa-large.svg';
import NetsuiteIconSquare129 from '@assets/images/integrationicons/netsuite-icon-square.svg';
import SimpleIllustrationWalletAlt130 from '@assets/images/simple-illustrations/simple-illustration__wallet-alt.svg';
import SimpleIllustrationBill131 from '@assets/images/simple-illustrations/simple-illustration__bill.svg';
import SimpleIllustrationSmartscan132 from '@assets/images/product-illustrations/simple-illustration__smartscan.svg';
import CharlesSchwab133 from '@assets/images/bank-icons/charles-schwab.svg';
import CardWellsfargoLarge134 from '@assets/images/companyCards/large/card-wellsfargo-large.svg';
import SimpleIllustrationPencil135 from '@assets/images/simple-illustrations/simple-illustration__pencil.svg';
import TadaYellow136 from '@assets/images/product-illustrations/tada--yellow.svg';
import SimpleIllustrationConciergeBubble137 from '@assets/images/simple-illustrations/simple-illustration__concierge-bubble.svg';
import TadaBlue138 from '@assets/images/product-illustrations/tada--blue.svg';
import ToddBehindCloud139 from '@assets/images/product-illustrations/todd-behind-cloud.svg';
import SimpleIllustrationInvoice140 from '@assets/images/simple-illustrations/simple-illustration__invoice.svg';
import SimpleIllustrationApproval141 from '@assets/images/simple-illustrations/simple-illustration__approval.svg';
import NetsuiteOracleIcon142 from '@assets/images/integrationicons/export/netsuite-oracle-icon.svg';
import SimpleIllustrationSendmoney143 from '@assets/images/simple-illustrations/simple-illustration__sendmoney.svg';
import SimpleIllustrationHourglass144 from '@assets/images/simple-illustrations/simple-illustration__hourglass.svg';
import SimpleIllustrationTreasurechest145 from '@assets/images/simple-illustrations/simple-illustration__treasurechest.svg';
import Discover146 from '@assets/images/cardicons/discover.svg';
import SimpleIllustrationMoneybadge147 from '@assets/images/simple-illustrations/simple-illustration__moneybadge.svg';
import SimpleIllustrationCarIce148 from '@assets/images/simple-illustrations/simple-illustration__car-ice.svg';
import SimpleIllustrationCar149 from '@assets/images/simple-illustrations/simple-illustration__car.svg';
import SimpleIllustrationConcierge150 from '@assets/images/simple-illustrations/simple-illustration__concierge.svg';
import SimpleIllustrationShield151 from '@assets/images/simple-illustrations/simple-illustration__shield.svg';
import SimpleIllustrationCarPink152 from '@assets/images/simple-illustrations/simple-illustration__car_pink.svg';
import CapitalOne153 from '@assets/images/bank-icons/capital-one.svg';
import SimpleIllustrationCreditCards154 from '@assets/images/simple-illustrations/simple-illustration__credit-cards.svg';
import SimpleIllustrationCoins155 from '@assets/images/simple-illustrations/simple-illustration__coins.svg';
import ReceiptsSearchYellow156 from '@assets/images/product-illustrations/receipts-search--yellow.svg';
import Citizens157 from '@assets/images/cardicons/citizens.svg';
import Discover158 from '@assets/images/bank-icons/discover.svg';
import SimpleIllustrationMailbox159 from '@assets/images/simple-illustrations/simple-illustration__mailbox.svg';
import SimpleIllustrationHeadset160 from '@assets/images/simple-illustrations/simple-illustration__headset.svg';
import BankMouseGreen161 from '@assets/images/product-illustrations/bank-mouse--green.svg';
import SimpleIllustrationSplitbill162 from '@assets/images/simple-illustrations/simple-illustration__splitbill.svg';
import SimpleIllustrationBinoculars163 from '@assets/images/simple-illustrations/simple-illustration__binoculars.svg';
import BankUserGreen164 from '@assets/images/product-illustrations/bank-user--green.svg';
import SimpleIllustrationSanfrancisco165 from '@assets/images/simple-illustrations/simple-illustration__sanfrancisco.svg';
import SimpleIllustrationLockclosed166 from '@assets/images/simple-illustrations/simple-illustration__lockclosed.svg';
import SimpleIllustrationLockopen167 from '@assets/images/simple-illustrations/simple-illustration__lockopen.svg';
import SimpleIllustrationSmartscan168 from '@assets/images/simple-illustrations/simple-illustration__smartscan.svg';
import SimpleIllustrationMobileapp169 from '@assets/images/simple-illustrations/simple-illustration__mobileapp.svg';
import EmptyStateAttachReceipt170 from '@assets/images/empty-state__attach-receipt.svg';
import SimpleIllustrationCreditcardsGreen171 from '@assets/images/simple-illustrations/simple-illustration__creditcards--green.svg';
import SimpleIllustrationTeachersUnite172 from '@assets/images/simple-illustrations/simple-illustration__teachers-unite.svg';
import SimpleIllustrationTrashcan173 from '@assets/images/simple-illustrations/simple-illustration__trashcan.svg';
import RegionsBank174 from '@assets/images/cardicons/regions-bank.svg';
import SimpleIllustrationVirtualcard175 from '@assets/images/simple-illustrations/simple-illustration__virtualcard.svg';
import CardWellsFargo176 from '@assets/images/companyCards/card-wells_fargo.svg';
import SimpleIllustrationCreditcardeyes177 from '@assets/images/simple-illustrations/simple-illustration__creditcardeyes.svg';
import BankArrowPink178 from '@assets/images/product-illustrations/bank-arrow--pink.svg';
import SimpleIllustrationLuggage179 from '@assets/images/simple-illustrations/simple-illustration__luggage.svg';
import JewelBoxYellow180 from '@assets/images/product-illustrations/jewel-box--yellow.svg';
import JewelBoxPink181 from '@assets/images/product-illustrations/jewel-box--pink.svg';
import JewelBoxGreen182 from '@assets/images/product-illustrations/jewel-box--green.svg';
import JewelBoxBlue183 from '@assets/images/product-illustrations/jewel-box--blue.svg';
import ExpensifyLogoAdhoc184 from '@assets/images/expensify-logo--adhoc.svg';
import CardStripe185 from '@assets/images/companyCards/card-stripe.svg';
import SimpleIllustrationAlert186 from '@assets/images/simple-illustrations/simple-illustration__alert.svg';
import SimpleIllustrationCoffeemug187 from '@assets/images/simple-illustrations/simple-illustration__coffeemug.svg';
import ExpensifyLogoStaging188 from '@assets/images/expensify-logo--staging.svg';
import Usaa189 from '@assets/images/cardicons/usaa.svg';
import CitizensBank190 from '@assets/images/bank-icons/citizens-bank.svg';
import SimpleIllustrationPalmtree191 from '@assets/images/simple-illustrations/simple-illustration__palmtree.svg';
import SimpleIllustrationHouse192 from '@assets/images/simple-illustrations/simple-illustration__house.svg';
import SimpleIllustrationFlash193 from '@assets/images/simple-illustrations/simple-illustration__flash.svg';
import OracleIcon194 from '@assets/images/integrationicons/export/oracle-icon.svg';
import SimpleIllustrationHandcard195 from '@assets/images/simple-illustrations/simple-illustration__handcard.svg';
import SimpleIllustrationMagnifyingglassMoney196 from '@assets/images/simple-illustrations/simple-illustration__magnifyingglass-money.svg';
import SimpleIllustrationAbacus197 from '@assets/images/simple-illustrations/simple-illustration__abacus.svg';
import NetsuiteIcon198 from '@assets/images/integrationicons/export/netsuite-icon.svg';
import CardStripeLarge199 from '@assets/images/companyCards/large/card-stripe-large.svg';
import SimpleIllustrationStopwatch200 from '@assets/images/simple-illustrations/simple-illustration__stopwatch.svg';
import ExpensifyLogoDev201 from '@assets/images/expensify-logo--dev.svg';
import XeroIconCircle202 from '@assets/images/integrationicons/xero-icon-circle.svg';
import XeroIconSquare203 from '@assets/images/integrationicons/xero-icon-square.svg';
import RegionsBank204 from '@assets/images/bank-icons/regions-bank.svg';
import SimpleIllustrationTire205 from '@assets/images/simple-illustrations/simple-illustration__tire.svg';
import ReceiptBody206 from '@assets/images/receipt-body.svg';
import SimpleIllustrationLockclosedOrange207 from '@assets/images/simple-illustrations/simple-illustration__lockclosed_orange.svg';
import Amex208 from '@assets/images/companyCards/amex.svg';
import CardCiti209 from '@assets/images/companyCards/card-citi.svg';
import CardAmex210 from '@assets/images/companyCards/card-amex.svg';
import XeroIcon211 from '@assets/images/integrationicons/export/xero-icon.svg';
import BbT212 from '@assets/images/cardicons/bb-t.svg';
import SimpleIllustrationCompanyCard213 from '@assets/images/simple-illustrations/simple-illustration__company-card.svg';
import UsBank214 from '@assets/images/cardicons/us-bank.svg';
import SimpleIllustrationEmailAddress215 from '@assets/images/simple-illustrations/simple-illustration__email-address.svg';
import SimpleIllustrationTag216 from '@assets/images/simple-illustrations/simple-illustration__tag.svg';
import SageIntacctIcon217 from '@assets/images/integrationicons/export/sage-intacct-icon.svg';
import Mastercard218 from '@assets/images/companyCards/mastercard.svg';
import Usaa219 from '@assets/images/bank-icons/usaa.svg';
import SimpleIllustrationHandearth220 from '@assets/images/simple-illustrations/simple-illustration__handearth.svg';
import SimpleIllustrationReceipt221 from '@assets/images/simple-illustrations/simple-illustration__receipt.svg';
import CardBofaLarge222 from '@assets/images/companyCards/large/card-bofa-large.svg';
import CardCitiLarge223 from '@assets/images/companyCards/large/card-citi-large.svg';
import CardBrex224 from '@assets/images/companyCards/card-brex.svg';
import SimpleIllustrationLightbulb225 from '@assets/images/simple-illustrations/simple-illustration__lightbulb.svg';
import ConciergeAvatar226 from '@assets/images/avatars/concierge-avatar.svg';
import ExpensifyFooterLogoVertical227 from '@assets/images/expensify-footer-logo-vertical.svg';
import ExpensifyFooterLogo228 from '@assets/images/expensify-footer-logo.svg';
import CardAmexLarge229 from '@assets/images/companyCards/large/card-amex-large.svg';
import SageIntacctIconSquare230 from '@assets/images/integrationicons/sage-intacct-icon-square.svg';
import MoneyMousePink231 from '@assets/images/product-illustrations/money-mouse--pink.svg';
import MccRentalcar232 from '@assets/images/MCCGroupIcons/MCC-RentalCar.svg';
import CarWithKey233 from '@assets/images/car-with-key.svg';
import CardMastercard234 from '@assets/images/companyCards/card-mastercard.svg';
import SimpleIllustrationTwocardsHorizontal235 from '@assets/images/simple-illustrations/simple-illustration__twocards-horizontal.svg';
import NewExpensifyAdhoc236 from '@assets/images/new-expensify-adhoc.svg';
import CardBofa237 from '@assets/images/companyCards/card-bofa.svg';
import MoneyEnvelopeBlue238 from '@assets/images/product-illustrations/money-envelope--blue.svg';
import ExpensifyWordmarkWhite239 from '@assets/images/expensify_wordmark_white.svg';
import ExpensifyLogoProd240 from '@assets/images/expensify-logo--prod.svg';
import CreditCardsBlue241 from '@assets/images/product-illustrations/credit-cards--blue.svg';
import GenericDarkLarge242 from '@assets/images/companyCards/large/generic-dark-large.svg';
import GenericLightLarge243 from '@assets/images/companyCards/large/generic-light-large.svg';
import NewExpensifyStg244 from '@assets/images/new-expensify-stg.svg';
import UsBank245 from '@assets/images/bank-icons/us-bank.svg';
import BbT246 from '@assets/images/bank-icons/bb-t.svg';
import OracleIconSquare247 from '@assets/images/integrationicons/oracle-icon-square.svg';
import CardBrexLarge248 from '@assets/images/companyCards/large/card-brex-large.svg';
import CardCapitalOneLarge249 from '@assets/images/companyCards/large/card-capital_one-large.svg';
import CardPlaidLarge250 from '@assets/images/companyCards/large/card-plaid-large.svg';
import CardChase251 from '@assets/images/companyCards/card-chase.svg';
import ArrowSplit252 from '@assets/images/arrow-split.svg';
import ExpensifyWordmark253 from '@assets/images/expensify-wordmark.svg';
import GpsTrackOrange254 from '@assets/images/product-illustrations/gps-track--orange.svg';
import CardMastercardLarge255 from '@assets/images/companyCards/large/card-mastercard-large.svg';
import Keyboard256 from '@assets/images/keyboard.svg';
import SimpleIllustrationFolderOpen257 from '@assets/images/simple-illustrations/simple-illustration__folder-open.svg';
import CardCapitalOne258 from '@assets/images/companyCards/card-capital_one.svg';
import DocumentMerge259 from '@assets/images/document-merge.svg';
import SimpleIllustrationSubscriptionPpu260 from '@assets/images/simple-illustrations/simple-illustration__subscription-ppu.svg';
import CardCapitalone261 from '@assets/images/companyCards/card-capitalone.svg';
import CardPlaid262 from '@assets/images/companyCards/card-plaid.svg';
import SimpleIllustrationChatbubbles263 from '@assets/images/simple-illustrations/simple-illustration__chatbubbles.svg';
import Coins264 from '@assets/images/coins.svg';
import CardChaseLarge265 from '@assets/images/companyCards/large/card-chase-large.svg';
import SocialInstagram266 from '@assets/images/social-instagram.svg';
import VolumeHigh267 from '@assets/images/volume-high.svg';
import GenericLight268 from '@assets/images/companyCards/generic-light.svg';
import GenericDark269 from '@assets/images/companyCards/generic-dark.svg';
import SimpleIllustrationCommentbubbles270 from '@assets/images/simple-illustrations/simple-illustration__commentbubbles.svg';
import SapIcon271 from '@assets/images/integrationicons/export/sap-icon.svg';
import GenericCsvLightLarge272 from '@assets/images/companyCards/large/generic-csv-light-large.svg';
import GenericCsvDarkLarge273 from '@assets/images/companyCards/large/generic-csv-dark-large.svg';
import MicrosoftDynamicsIcon274 from '@assets/images/integrationicons/export/microsoft-dynamics-icon.svg';
import SimpleIllustrationCommentbubblesBlue275 from '@assets/images/simple-illustrations/simple-illustration__commentbubbles_blue.svg';
import ExpensifyLogoNew276 from '@assets/images/expensify-logo-new.svg';
import MccTaxi277 from '@assets/images/MCCGroupIcons/MCC-Taxi.svg';
import InvoiceOrange278 from '@assets/images/product-illustrations/invoice--orange.svg';
import SimpleIllustrationCheckmarkcircle279 from '@assets/images/simple-illustrations/simple-illustration__checkmarkcircle.svg';
import AmericanExpress280 from '@assets/images/cardicons/american-express.svg';
import NewExpensify281 from '@assets/images/new-expensify.svg';
import SimpleIllustrationReceiptupload282 from '@assets/images/simple-illustrations/simple-illustration__receiptupload.svg';
import SimpleIllustrationBuildings283 from '@assets/images/simple-illustrations/simple-illustration__buildings.svg';
import SimpleIllustrationRules284 from '@assets/images/simple-illustrations/simple-illustration__rules.svg';
import NewExpensifyDev285 from '@assets/images/new-expensify-dev.svg';
import NotificationsAvatar286 from '@assets/images/avatars/notifications-avatar.svg';
import CreditCardHourglass287 from '@assets/images/credit-card-hourglass.svg';
import MccGroceries288 from '@assets/images/MCCGroupIcons/MCC-Groceries.svg';
import ConciergeExclamation289 from '@assets/images/product-illustrations/concierge--exclamation.svg';
import AddReaction290 from '@assets/images/add-reaction.svg';
import MicrosoftDynamicsIconSquare291 from '@assets/images/integrationicons/microsoft-dynamics-icon-square.svg';
import Gear292 from '@assets/images/gear.svg';
import Train293 from '@assets/images/train.svg';
import BankOfAmerica294 from '@assets/images/cardicons/bank-of-america.svg';
import NewWorkspace295 from '@assets/images/new-workspace.svg';
import Fidelity296 from '@assets/images/cardicons/fidelity.svg';
import Citibank297 from '@assets/images/cardicons/citibank.svg';
import MccCommuter298 from '@assets/images/MCCGroupIcons/MCC-Commuter.svg';
import Ereceipticon299 from '@assets/images/eReceiptIcon.svg';
import GenericCsvLight300 from '@assets/images/companyCards/generic-csv-light.svg';
import GenericCsvDark301 from '@assets/images/companyCards/generic-csv-dark.svg';
import ReceiptMultiple302 from '@assets/images/receipt-multiple.svg';
import MccMeals303 from '@assets/images/MCCGroupIcons/MCC-Meals.svg';
import MccUtilities304 from '@assets/images/MCCGroupIcons/MCC-Utilities.svg';
import EmptystateRoutepending305 from '@assets/images/emptystate__routepending.svg';
import AddEmoji306 from '@assets/images/emojiCategoryIcons/add-emoji.svg';
import AmericanExpress307 from '@assets/images/bank-icons/american-express.svg';
import GoogleLogo308 from '@assets/images/signIn/google-logo.svg';
import Hashtag309 from '@assets/images/hashtag.svg';
import ExpensifyAppIcon310 from '@assets/images/expensify-app-icon.svg';
import ReceiptScan311 from '@assets/images/receipt-scan.svg';
import Filters312 from '@assets/images/filters.svg';
import SocialPodcast313 from '@assets/images/social-podcast.svg';
import Wrench314 from '@assets/images/wrench.svg';
import Workflows315 from '@assets/images/workflows.svg';
import NewExpensifyDark316 from '@assets/images/new-expensify-dark.svg';
import ReceiptYellow317 from '@assets/images/product-illustrations/receipt--yellow.svg';
import Thread318 from '@assets/images/thread.svg';
import DefaultAvatar9319 from '@assets/images/avatars/group/default-avatar_9.svg';
import DefaultAvatar7320 from '@assets/images/avatars/group/default-avatar_7.svg';
import DefaultAvatar8321 from '@assets/images/avatars/group/default-avatar_8.svg';
import DefaultAvatar6322 from '@assets/images/avatars/group/default-avatar_6.svg';
import DefaultAvatar5323 from '@assets/images/avatars/group/default-avatar_5.svg';
import DefaultAvatar3324 from '@assets/images/avatars/group/default-avatar_3.svg';
import DefaultAvatar4325 from '@assets/images/avatars/group/default-avatar_4.svg';
import DefaultAvatar2326 from '@assets/images/avatars/group/default-avatar_2.svg';
import DefaultAvatar17327 from '@assets/images/avatars/group/default-avatar_17.svg';
import DefaultAvatar16328 from '@assets/images/avatars/group/default-avatar_16.svg';
import DefaultAvatar14329 from '@assets/images/avatars/group/default-avatar_14.svg';
import DefaultAvatar13330 from '@assets/images/avatars/group/default-avatar_13.svg';
import DefaultAvatar12331 from '@assets/images/avatars/group/default-avatar_12.svg';
import DefaultAvatar11332 from '@assets/images/avatars/group/default-avatar_11.svg';
import DefaultAvatar10333 from '@assets/images/avatars/group/default-avatar_10.svg';
import DefaultAvatar18334 from '@assets/images/avatars/group/default-avatar_18.svg';
import DefaultAvatar1335 from '@assets/images/avatars/group/default-avatar_1.svg';
import DefaultAvatar15336 from '@assets/images/avatars/group/default-avatar_15.svg';
import QboIcon337 from '@assets/images/integrationicons/export/qbo-icon.svg';
import HuntingtonBank338 from '@assets/images/cardicons/huntington-bank.svg';
import BankOfAmerica339 from '@assets/images/bank-icons/bank-of-america.svg';
import Receipt340 from '@assets/images/receipt.svg';
import Fullscreen341 from '@assets/images/fullscreen.svg';
import AppleLogo342 from '@assets/images/signIn/apple-logo.svg';
import Citibank343 from '@assets/images/bank-icons/citibank.svg';
import ReceiptSearch344 from '@assets/images/receipt-search.svg';
import SapIconSquare345 from '@assets/images/integrationicons/sap-icon-square.svg';
import Car346 from '@assets/images/car.svg';
import Car347 from '@assets/images/emojiCategoryIcons/car.svg';
import Fidelity348 from '@assets/images/bank-icons/fidelity.svg';
import DragAndDrop349 from '@assets/images/drag-and-drop.svg';
import Bug350 from '@assets/images/bug.svg';
import Crosshair351 from '@assets/images/crosshair.svg';
import Buildings352 from '@assets/images/buildings.svg';
import AdminRoom353 from '@assets/images/avatars/admin-room.svg';
import Meter354 from '@assets/images/meter.svg';
import SimpleIllustrationProfile355 from '@assets/images/simple-illustrations/simple-illustration__profile.svg';
import Pnc356 from '@assets/images/cardicons/pnc.svg';
import DomainRoom357 from '@assets/images/avatars/domain-room.svg';
import Bellslash358 from '@assets/images/bellSlash.svg';
import Binoculars359 from '@assets/images/binoculars.svg';
import Mute360 from '@assets/images/mute.svg';
import MoneyHourglass361 from '@assets/images/money-hourglass.svg';
import ReceiptSlash362 from '@assets/images/receipt-slash.svg';
import DefaultAvatarX363 from '@assets/images/avatars/workspace/default-avatar_x.svg';
import AnnounceRoom364 from '@assets/images/avatars/announce-room.svg';
import ConciergeBlue365 from '@assets/images/product-illustrations/concierge--blue.svg';
import ImageCropSquareMask366 from '@assets/images/image-crop-square-mask.svg';
import DefaultAvatarW367 from '@assets/images/avatars/workspace/default-avatar_w.svg';
import MccGas368 from '@assets/images/MCCGroupIcons/MCC-Gas.svg';
import VolumeLow369 from '@assets/images/volume-low.svg';
import ReceiptPlus370 from '@assets/images/receipt-plus.svg';
import HuntingtonBank371 from '@assets/images/bank-icons/huntington-bank.svg';
import SimpleIllustrationBuilding372 from '@assets/images/simple-illustrations/simple-illustration__building.svg';
import CommentBubbles373 from '@assets/images/comment-bubbles.svg';
import UserLock374 from '@assets/images/user-lock.svg';
import InvoiceGeneric375 from '@assets/images/invoice-generic.svg';
import Paycheck376 from '@assets/images/paycheck.svg';
import DefaultAvatarH377 from '@assets/images/avatars/workspace/default-avatar_h.svg';
import Task378 from '@assets/images/task.svg';
import SimpleIllustrationReceiptEnvelope379 from '@assets/images/simple-illustrations/simple-illustration__receipt-envelope.svg';
import DefaultAvatarM380 from '@assets/images/avatars/workspace/default-avatar_m.svg';
import LinkCopy381 from '@assets/images/link-copy.svg';
import DefaultAvatarE382 from '@assets/images/avatars/workspace/default-avatar_e.svg';
import Filter383 from '@assets/images/filter.svg';
import Android384 from '@assets/images/android.svg';
import ImageCropCircleMask385 from '@assets/images/image-crop-circle-mask.svg';
import VideoSlash386 from '@assets/images/video-slash.svg';
import MccMisc387 from '@assets/images/MCCGroupIcons/MCC-Misc.svg';
import CreditCardExclamation388 from '@assets/images/credit-card-exclamation.svg';
import DefaultAvatarK389 from '@assets/images/avatars/workspace/default-avatar_k.svg';
import Expensify390 from '@assets/images/bank-icons/expensify.svg';
import Suitcase391 from '@assets/images/suitcase.svg';
import UserEye392 from '@assets/images/user-eye.svg';
import DocumentPlus393 from '@assets/images/document-plus.svg';
import DefaultAvatarR394 from '@assets/images/avatars/workspace/default-avatar_r.svg';
import FallbackWorkspaceAvatar395 from '@assets/images/avatars/fallback-workspace-avatar.svg';
import MakeAdmin396 from '@assets/images/make-admin.svg';
import DefaultAvatarA397 from '@assets/images/avatars/workspace/default-avatar_a.svg';
import Globe398 from '@assets/images/globe.svg';
import GenericBankAccount399 from '@assets/images/bank-icons/generic-bank-account.svg';
import DefaultAvatarB400 from '@assets/images/avatars/workspace/default-avatar_b.svg';
import Shield401 from '@assets/images/shield.svg';
import SimpleIllustrationReportReceipt402 from '@assets/images/simple-illustrations/simple-illustration__report-receipt.svg';
import Pnc403 from '@assets/images/bank-icons/pnc.svg';
import MoneySearch404 from '@assets/images/money-search.svg';
import WorkspaceDefaultAvatar405 from '@assets/images/workspace-default-avatar.svg';
import TreasureChest406 from '@assets/images/treasure-chest.svg';
import EyeDisabled407 from '@assets/images/eye-disabled.svg';
import DeletedRoom408 from '@assets/images/avatars/deleted-room.svg';
import DefaultAvatarN409 from '@assets/images/avatars/workspace/default-avatar_n.svg';
import Exit410 from '@assets/images/exit.svg';
import MccHotel411 from '@assets/images/MCCGroupIcons/MCC-Hotel.svg';
import Stopwatch412 from '@assets/images/stopwatch.svg';
import DefaultAvatarF413 from '@assets/images/avatars/workspace/default-avatar_f.svg';
import MccServices414 from '@assets/images/MCCGroupIcons/MCC-Services.svg';
import DefaultAvatarY415 from '@assets/images/avatars/workspace/default-avatar_y.svg';
import Room416 from '@assets/images/avatars/room.svg';
import All417 from '@assets/images/all.svg';
import Apple418 from '@assets/images/apple.svg';
import ThumbsUp419 from '@assets/images/thumbs-up.svg';
import UserCheck420 from '@assets/images/user-check.svg';
import DefaultAvatarS421 from '@assets/images/avatars/workspace/default-avatar_s.svg';
import Hourglass422 from '@assets/images/hourglass.svg';
import DefaultAvatarZ423 from '@assets/images/avatars/workspace/default-avatar_z.svg';
import MoneyCircle424 from '@assets/images/money-circle.svg';
import QboIconCircle425 from '@assets/images/integrationicons/qbo-icon-circle.svg';
import Megaphone426 from '@assets/images/megaphone.svg';
import Luggage427 from '@assets/images/luggage.svg';
import QboIconSquare428 from '@assets/images/integrationicons/qbo-icon-square.svg';
import QbdIconSquare429 from '@assets/images/integrationicons/qbd-icon-square.svg';
import Connect430 from '@assets/images/connect.svg';
import ArrowCollapse431 from '@assets/images/arrow-collapse.svg';
import Bed432 from '@assets/images/bed.svg';
import Scan433 from '@assets/images/scan.svg';
import MccAirlines434 from '@assets/images/MCCGroupIcons/MCC-Airlines.svg';
import RotateImage435 from '@assets/images/rotate-image.svg';
import Qrcode436 from '@assets/images/qrcode.svg';
import Chatbubbles437 from '@assets/images/chatbubbles.svg';
import DefaultAvatarT438 from '@assets/images/avatars/workspace/default-avatar_t.svg';
import DefaultAvatar2439 from '@assets/images/avatars/workspace/default-avatar_2.svg';
import DefaultAvatarBuilding440 from '@assets/images/avatars/workspace/default-avatar_building.svg';
import SimpleIllustrationQrCode441 from '@assets/images/simple-illustrations/simple-illustration__qr-code.svg';
import MultiTag442 from '@assets/images/multi-tag.svg';
import Concierge443 from '@assets/images/concierge.svg';
import DefaultAvatarP444 from '@assets/images/avatars/workspace/default-avatar_p.svg';
import DefaultAvatar3445 from '@assets/images/avatars/workspace/default-avatar_3.svg';
import ChatbubbleReply446 from '@assets/images/chatbubble-reply.svg';
import FlagLevel03447 from '@assets/images/flag_level_03.svg';
import FlagLevel02448 from '@assets/images/flag_level_02.svg';
import FlagLevel01449 from '@assets/images/flag_level_01.svg';
import Sync450 from '@assets/images/sync.svg';
import ChatbubbleAdd451 from '@assets/images/chatbubble-add.svg';
import Eye452 from '@assets/images/eye.svg';
import DefaultAvatarG453 from '@assets/images/avatars/workspace/default-avatar_g.svg';
import DocumentSlash454 from '@assets/images/document-slash.svg';
import Building455 from '@assets/images/building.svg';
import Calendar456 from '@assets/images/calendar.svg';
import Calendar457 from '@assets/images/emojiCategoryIcons/calendar.svg';
import Zoom458 from '@assets/images/zoom.svg';
import DefaultAvatarD459 from '@assets/images/avatars/workspace/default-avatar_d.svg';
import DefaultAvatarQ460 from '@assets/images/avatars/workspace/default-avatar_q.svg';
import GalleryNotFound461 from '@assets/images/gallery-not-found.svg';
import AttachmentNotFound462 from '@assets/images/attachment-not-found.svg';
import XCircle463 from '@assets/images/x-circle.svg';
import ArrowUpLong464 from '@assets/images/arrow-up-long.svg';
import Link465 from '@assets/images/link.svg';
import Printer466 from '@assets/images/printer.svg';
import DefaultAvatarC467 from '@assets/images/avatars/workspace/default-avatar_c.svg';
import DefaultAvatarV468 from '@assets/images/avatars/workspace/default-avatar_v.svg';
import DefaultAvatarL469 from '@assets/images/avatars/workspace/default-avatar_l.svg';
import Chase470 from '@assets/images/bank-icons/chase.svg';
import ClosedSign471 from '@assets/images/closed-sign.svg';
import ArrowDownLong472 from '@assets/images/arrow-down-long.svg';
import Bank473 from '@assets/images/bank.svg';
import LightBulb474 from '@assets/images/emojiCategoryIcons/light-bulb.svg';
import Tag475 from '@assets/images/tag.svg';
import Bell476 from '@assets/images/bell.svg';
import DefaultAvatar8477 from '@assets/images/avatars/workspace/default-avatar_8.svg';
import Paypal478 from '@assets/images/paypal.svg';
import Chase479 from '@assets/images/cardicons/chase.svg';
import ChatbubbleUnread480 from '@assets/images/chatbubble-unread.svg';
import Plane481 from '@assets/images/plane.svg';
import DefaultAvatarU482 from '@assets/images/avatars/workspace/default-avatar_u.svg';
import Monitor483 from '@assets/images/monitor.svg';
import QuestionMarkCircle484 from '@assets/images/question-mark-circle.svg';
import MccMail485 from '@assets/images/MCCGroupIcons/MCC-Mail.svg';
import DefaultAvatar9486 from '@assets/images/avatars/workspace/default-avatar_9.svg';
import ArrowCircleClockwise487 from '@assets/images/arrow-circle-clockwise.svg';
import DefaultAvatar5488 from '@assets/images/avatars/workspace/default-avatar_5.svg';
import History489 from '@assets/images/history.svg';
import Trashcan490 from '@assets/images/trashcan.svg';
import SocialYoutube491 from '@assets/images/social-youtube.svg';
import DefaultAvatar6492 from '@assets/images/avatars/workspace/default-avatar_6.svg';
import CircularArrowBackwards493 from '@assets/images/circular-arrow-backwards.svg';
import Offline494 from '@assets/images/offline.svg';
import Rotate495 from '@assets/images/rotate.svg';
import Gallery496 from '@assets/images/gallery.svg';
import NewWindow497 from '@assets/images/new-window.svg';
import MoneyBag498 from '@assets/images/money-bag.svg';
import Pin499 from '@assets/images/pin.svg';
import Map500 from '@assets/images/map.svg';
import Transfer501 from '@assets/images/transfer.svg';
import Users502 from '@assets/images/users.svg';
import ArrowsUpdown503 from '@assets/images/arrows-updown.svg';
import DefaultAvatar7504 from '@assets/images/avatars/workspace/default-avatar_7.svg';
import Paperclip505 from '@assets/images/paperclip.svg';
import BoltSlash506 from '@assets/images/bolt-slash.svg';
import DefaultAvatar1507 from '@assets/images/avatars/workspace/default-avatar_1.svg';
import UserPlus508 from '@assets/images/user-plus.svg';
import Feed509 from '@assets/images/feed.svg';
import TdBank510 from '@assets/images/cardicons/td-bank.svg';
import DefaultAvatarJ511 from '@assets/images/avatars/workspace/default-avatar_j.svg';
import PeaceSign512 from '@assets/images/emojiCategoryIcons/peace-sign.svg';
import Info513 from '@assets/images/info.svg';
import HomeFadeGradient514 from '@assets/images/home-fade-gradient.svg';
import HomeFadeGradientMobile515 from '@assets/images/home-fade-gradient--mobile.svg';
import SocialTwitter516 from '@assets/images/social-twitter.svg';
import Star517 from '@assets/images/Star.svg';
import Chair518 from '@assets/images/chair.svg';
import Download519 from '@assets/images/download.svg';
import CaretUpDown520 from '@assets/images/caret-up-down.svg';
import Invoice521 from '@assets/images/invoice.svg';
import Bill522 from '@assets/images/bill.svg';
import UploadAlt523 from '@assets/images/upload-alt.svg';
import Collapse524 from '@assets/images/collapse.svg';
import Upload525 from '@assets/images/upload.svg';
import CheckmarkCircle526 from '@assets/images/checkmark-circle.svg';
import Key527 from '@assets/images/key.svg';
import DefaultAvatar4528 from '@assets/images/avatars/workspace/default-avatar_4.svg';
import Menu529 from '@assets/images/menu.svg';
import Emoji530 from '@assets/images/emoji.svg';
import Camera531 from '@assets/images/camera.svg';
import Plane532 from '@assets/images/emojiCategoryIcons/plane.svg';
import Expand533 from '@assets/images/expand.svg';
import DefaultAvatarI534 from '@assets/images/avatars/workspace/default-avatar_i.svg';
import Export535 from '@assets/images/export.svg';
import ChatbubbleSlash536 from '@assets/images/chatbubble-slash.svg';
import MagnifyingGlass537 from '@assets/images/magnifying-glass.svg';
import ArrowsLeftright538 from '@assets/images/arrows-leftright.svg';
import OfflineCloud539 from '@assets/images/offline-cloud.svg';
import Hamburger540 from '@assets/images/emojiCategoryIcons/hamburger.svg';
import ThreeDots541 from '@assets/images/three-dots.svg';
import TdBank542 from '@assets/images/bank-icons/td-bank.svg';
import RotateLeft543 from '@assets/images/rotate-left.svg';
import Shutter544 from '@assets/images/shutter.svg';
import Plant545 from '@assets/images/emojiCategoryIcons/plant.svg';
import Pause546 from '@assets/images/pause.svg';
import Briefcase547 from '@assets/images/briefcase.svg';
import Wallet548 from '@assets/images/wallet.svg';
import ChatbubbleCounter549 from '@assets/images/chatbubble-counter.svg';
import SoccerBall550 from '@assets/images/emojiCategoryIcons/soccer-ball.svg';
import MccGoods551 from '@assets/images/MCCGroupIcons/MCC-Goods.svg';
import RemoveMembers552 from '@assets/images/remove-members.svg';
import Home553 from '@assets/images/home.svg';
import ReceiptPlaceholderPlus554 from '@assets/images/receipt-placeholder-plus.svg';
import DotIndicatorUnfilled555 from '@assets/images/dot-indicator-unfilled.svg';
import Box556 from '@assets/images/box.svg';
import Inbox557 from '@assets/images/inbox.svg';
import Phone558 from '@assets/images/phone.svg';
import DefaultAvatarO559 from '@assets/images/avatars/workspace/default-avatar_o.svg';
import DefaultAvatar0560 from '@assets/images/avatars/workspace/default-avatar_0.svg';
import Lock561 from '@assets/images/lock.svg';
import CalendarSolid562 from '@assets/images/calendar-solid.svg';
import Pencil563 from '@assets/images/pencil.svg';
import ArrowRightLong564 from '@assets/images/arrow-right-long.svg';
import Mail565 from '@assets/images/mail.svg';
import FallbackAvatar566 from '@assets/images/avatars/fallback-avatar.svg';
import SocialLinkedin567 from '@assets/images/social-linkedin.svg';
import Exclamation568 from '@assets/images/exclamation.svg';
import CheckCircle569 from '@assets/images/check-circle.svg';
import Close570 from '@assets/images/close.svg';
import CheckSquare571 from '@assets/images/check-square.svg';
import Document572 from '@assets/images/document.svg';
import Profile573 from '@assets/images/profile.svg';
import Flag574 from '@assets/images/flag.svg';
import Flag575 from '@assets/images/emojiCategoryIcons/flag.svg';
import Checkmark576 from '@assets/images/checkmark.svg';
import Location577 from '@assets/images/location.svg';
import ArrowUp578 from '@assets/images/arrow-up.svg';
import Down579 from '@assets/images/down.svg';
import Creditcard580 from '@assets/images/creditcard.svg';
import ArrowRight581 from '@assets/images/arrow-right.svg';
import Copy582 from '@assets/images/copy.svg';
import Checkbox583 from '@assets/images/checkbox.svg';
import BackLeft584 from '@assets/images/back-left.svg';
import Chatbubble585 from '@assets/images/chatbubble.svg';
import Send586 from '@assets/images/send.svg';
import Cash587 from '@assets/images/cash.svg';
import User588 from '@assets/images/user.svg';
import ExpensifyCardIcon589 from '@assets/images/expensify-card-icon.svg';
import CircleSlash590 from '@assets/images/integrationicons/circle-slash.svg';
import Heart591 from '@assets/images/heart.svg';
import Heart592 from '@assets/images/emojiCategoryIcons/heart.svg';
import Plus593 from '@assets/images/plus.svg';
import DragHandles594 from '@assets/images/drag-handles.svg';
import Unlock595 from '@assets/images/unlock.svg';
import Bookmark596 from '@assets/images/bookmark.svg';
import SocialFacebook597 from '@assets/images/social-facebook.svg';
import GenericBankCard598 from '@assets/images/cardicons/generic-bank-card.svg';
import Table599 from '@assets/images/table.svg';
import Bolt600 from '@assets/images/bolt.svg';
import Play601 from '@assets/images/play.svg';
import EmptySquare602 from '@assets/images/empty-square.svg';
import Minus603 from '@assets/images/minus.svg';
import DotIndicator604 from '@assets/images/dot-indicator.svg';
import Folder605 from '@assets/images/folder.svg';

export type SVGItem = {
    position: number;
    name: string;
    component: React.ComponentType<any>;
};

// Complete SVG items array (605 total)
export const svgItems: SVGItem[] = [
    {position: 1, name: 'home-background--ios.svg', component: HomeBackgroundIos1},
    {position: 2, name: 'home-background--desktop.svg', component: HomeBackgroundDesktop2},
    {position: 3, name: 'home-background--mobile.svg', component: HomeBackgroundMobile3},
    {position: 4, name: 'home-background--android.svg', component: HomeBackgroundAndroid4},
    {position: 5, name: 'lounge.svg', component: Lounge5},
    {position: 6, name: 'olddot-wireframe.svg', component: OlddotWireframe6},
    {position: 7, name: 'eReceipt_background.svg', component: EreceiptBackground7},
    {position: 8, name: 'test-drive.svg', component: TestDrive8},
    {position: 9, name: 'illustration__card-replacement-success.svg', component: IllustrationCardReplacementSuccess9},
    {position: 10, name: 'simple-illustration__empty-shelves.svg', component: SimpleIllustrationEmptyShelves10},
    {position: 11, name: 'emptystate__expensifycard.svg', component: EmptystateExpensifycard11},
    {position: 12, name: 'emptystate__holdexpense.svg', component: EmptystateHoldexpense12},
    {position: 13, name: 'eReceipt-BGImage.svg', component: EreceiptBgimage13},
    {position: 14, name: 'eReceiptBG_tangerine.svg', component: EreceiptbgTangerine14},
    {position: 15, name: 'eReceiptBG_pink.svg', component: EreceiptbgPink15},
    {position: 16, name: 'todd-in-car.svg', component: ToddInCar16},
    {position: 17, name: 'todd-with-phones.svg', component: ToddWithPhones17},
    {position: 18, name: 'eReceiptBG_yellow.svg', component: EreceiptbgYellow18},
    {position: 19, name: 'magic-code.svg', component: MagicCode19},
    {position: 20, name: 'emptystate__card-pos.svg', component: EmptystateCardPos20},
    {position: 21, name: 'eReceiptBG_ice.svg', component: EreceiptbgIce21},
    {position: 22, name: 'abracadabra.svg', component: Abracadabra22},
    {position: 23, name: 'eReceiptBG_green.svg', component: EreceiptbgGreen23},
    {position: 24, name: 'emptystate__travel.svg', component: EmptystateTravel24},
    {position: 25, name: 'emptystate__receiptfairy.svg', component: EmptystateReceiptfairy25},
    {position: 26, name: 'eReceiptBG_blue.svg', component: EreceiptbgBlue26},
    {position: 27, name: 'home-illustration-hands.svg', component: HomeIllustrationHands27},
    {position: 28, name: 'laptop-with-second-screen-x.svg', component: LaptopWithSecondScreenX28},
    {position: 29, name: 'cardIllustration.svg', component: Cardillustration29},
    {position: 30, name: 'magnifying-glass-spy-mouth-closed.svg', component: MagnifyingGlassSpyMouthClosed30},
    {position: 31, name: 'spreadsheet-computer.svg', component: SpreadsheetComputer31},
    {position: 32, name: 'payment-hands.svg', component: PaymentHands32},
    {position: 33, name: 'educational-illustration__multi-scan.svg', component: EducationalIllustrationMultiScan33},
    {position: 34, name: 'emptystate__big-vault.svg', component: EmptystateBigVault34},
    {position: 35, name: 'laptop-with-second-screen-and-hourglass.svg', component: LaptopWithSecondScreenAndHourglass35},
    {position: 36, name: 'pending-bank.svg', component: PendingBank36},
    {position: 37, name: 'connection-complete.svg', component: ConnectionComplete37},
    {position: 38, name: 'rocket-dude.svg', component: RocketDude38},
    {position: 39, name: 'money-stack.svg', component: MoneyStack39},
    {position: 40, name: 'laptop-with-second-screen-sync.svg', component: LaptopWithSecondScreenSync40},
    {position: 41, name: 'computer.svg', component: Computer41},
    {position: 42, name: 'pendingstate_laptop-with-hourglass-and-cards.svg', component: PendingstateLaptopWithHourglassAndCards42},
    {position: 43, name: 'running-turtle.svg', component: RunningTurtle43},
    {position: 44, name: 'simple-illustration__bigrocket.svg', component: SimpleIllustrationBigrocket44},
    {position: 45, name: 'simple-illustration__gears.svg', component: SimpleIllustrationGears45},
    {position: 46, name: 'money-waving.svg', component: MoneyWaving46},
    {position: 47, name: 'simple-illustration__hotdogstand.svg', component: SimpleIllustrationHotdogstand47},
    {position: 48, name: 'rocket--blue.svg', component: RocketBlue48},
    {position: 49, name: 'hand.svg', component: Hand49},
    {position: 50, name: 'suntrust.svg', component: Suntrust50},
    {position: 51, name: 'default-avatar_16.svg', component: DefaultAvatar1651},
    {position: 52, name: 'three_legged_laptop_woman.svg', component: ThreeLeggedLaptopWoman52},
    {position: 53, name: 'default-avatar_24.svg', component: DefaultAvatar2453},
    {position: 54, name: 'suntrust.svg', component: Suntrust54},
    {position: 55, name: 'default-avatar_3.svg', component: DefaultAvatar355},
    {position: 56, name: 'advanced-approvals-icon-square.svg', component: AdvancedApprovalsIconSquare56},
    {position: 57, name: 'simple-illustration__piggybank.svg', component: SimpleIllustrationPiggybank57},
    {position: 58, name: 'default-avatar_4.svg', component: DefaultAvatar458},
    {position: 59, name: 'emptystate__expenses.svg', component: EmptystateExpenses59},
    {position: 60, name: 'simple-illustration__receipt-location-marker.svg', component: SimpleIllustrationReceiptLocationMarker60},
    {position: 61, name: 'default-avatar_7.svg', component: DefaultAvatar761},
    {position: 62, name: 'mushroom-top-hat.svg', component: MushroomTopHat62},
    {position: 63, name: 'default-avatar_13.svg', component: DefaultAvatar1363},
    {position: 64, name: 'default-avatar_14.svg', component: DefaultAvatar1464},
    {position: 65, name: 'default-avatar_22.svg', component: DefaultAvatar2265},
    {position: 66, name: 'uber.svg', component: Uber66},
    {position: 67, name: 'default-avatar_23.svg', component: DefaultAvatar2367},
    {position: 68, name: 'default-avatar_5.svg', component: DefaultAvatar568},
    {position: 69, name: 'default-avatar_20.svg', component: DefaultAvatar2069},
    {position: 70, name: 'simple-illustration__workflows.svg', component: SimpleIllustrationWorkflows70},
    {position: 71, name: 'simple-illustration__filters.svg', component: SimpleIllustrationFilters71},
    {position: 72, name: 'default-avatar_6.svg', component: DefaultAvatar672},
    {position: 73, name: 'default-avatar_15.svg', component: DefaultAvatar1573},
    {position: 74, name: 'default-avatar_10.svg', component: DefaultAvatar1074},
    {position: 75, name: 'default-avatar_8.svg', component: DefaultAvatar875},
    {position: 76, name: 'simple-illustration__opensafe.svg', component: SimpleIllustrationOpensafe76},
    {position: 77, name: 'default-avatar_1.svg', component: DefaultAvatar177},
    {position: 78, name: 'default-avatar_19.svg', component: DefaultAvatar1978},
    {position: 79, name: 'emptystate__spy-pigeon.svg', component: EmptystateSpyPigeon79},
    {position: 80, name: 'default-avatar_21.svg', component: DefaultAvatar2180},
    {position: 81, name: 'default-avatar_11.svg', component: DefaultAvatar1181},
    {position: 82, name: 'default-avatar_17.svg', component: DefaultAvatar1782},
    {position: 83, name: 'receipts-stacked-on-pin.svg', component: ReceiptsStackedOnPin83},
    {position: 84, name: 'simple-illustration__smallrocket.svg', component: SimpleIllustrationSmallrocket84},
    {position: 85, name: 'safe.svg', component: Safe85},
    {position: 86, name: 'card-expensify.svg', component: CardExpensify86},
    {position: 87, name: 'receipt-upload.svg', component: ReceiptUpload87},
    {position: 88, name: 'subscription-details__approvedlogo.svg', component: SubscriptionDetailsApprovedlogo88},
    {position: 89, name: 'default-avatar_12.svg', component: DefaultAvatar1289},
    {position: 90, name: 'subscription-details__approvedlogo--light.svg', component: SubscriptionDetailsApprovedlogoLight90},
    {position: 91, name: 'simple-illustration__receipt-wrangler.svg', component: SimpleIllustrationReceiptWrangler91},
    {position: 92, name: 'navy-federal-credit-union.svg', component: NavyFederalCreditUnion92},
    {position: 93, name: 'emptystate__puzzlepieces.svg', component: EmptystatePuzzlepieces93},
    {position: 94, name: 'turtle-in-shell.svg', component: TurtleInShell94},
    {position: 95, name: 'simple-illustration__moneywings.svg', component: SimpleIllustrationMoneywings95},
    {position: 96, name: 'default-avatar_18.svg', component: DefaultAvatar1896},
    {position: 97, name: 'simple-illustration__accounting.svg', component: SimpleIllustrationAccounting97},
    {position: 98, name: 'card-expensify-large.svg', component: CardExpensifyLarge98},
    {position: 99, name: 'simple-illustration__money-receipts.svg', component: SimpleIllustrationMoneyReceipts99},
    {position: 100, name: 'simple-illustration__messageinabottle.svg', component: SimpleIllustrationMessageinabottle100},
    {position: 101, name: 'simple-illustration__bank-arrow.svg', component: SimpleIllustrationBankArrow101},
    {position: 102, name: 'simple-illustration__empty-state.svg', component: SimpleIllustrationEmptyState102},
    {position: 103, name: 'simple-illustration__subscription-annual.svg', component: SimpleIllustrationSubscriptionAnnual103},
    {position: 104, name: 'simple-illustration__perdiem.svg', component: SimpleIllustrationPerdiem104},
    {position: 105, name: 'simple-illustration__pillow.svg', component: SimpleIllustrationPillow105},
    {position: 106, name: 'broken-magnifying-glass.svg', component: BrokenMagnifyingGlass106},
    {position: 107, name: 'expensify-card-dark.svg', component: ExpensifyCardDark107},
    {position: 108, name: 'charles-schwab.svg', component: CharlesSchwab108},
    {position: 109, name: 'rocket--orange.svg', component: RocketOrange109},
    {position: 110, name: 'simple-illustration__encryption.svg', component: SimpleIllustrationEncryption110},
    {position: 111, name: 'default-avatar_2.svg', component: DefaultAvatar2111},
    {position: 112, name: 'folder-with-papers.svg', component: FolderWithPapers112},
    {position: 113, name: 'visa.svg', component: Visa113},
    {position: 114, name: 'simple-illustration__envelopereceipt.svg', component: SimpleIllustrationEnvelopereceipt114},
    {position: 115, name: 'default-avatar_9.svg', component: DefaultAvatar9115},
    {position: 116, name: 'card-visa.svg', component: CardVisa116},
    {position: 117, name: 'navy-federal-credit-union.svg', component: NavyFederalCreditUnion117},
    {position: 118, name: 'simple-illustration__thumbsupstars.svg', component: SimpleIllustrationThumbsupstars118},
    {position: 119, name: 'simple-illustration__realtimereports.svg', component: SimpleIllustrationRealtimereports119},
    {position: 120, name: 'expensify-card.svg', component: ExpensifyCard120},
    {position: 121, name: 'simple-illustration__moneyintowallet.svg', component: SimpleIllustrationMoneyintowallet121},
    {position: 122, name: 'simple-illustration__replace-receipt.svg', component: SimpleIllustrationReplaceReceipt122},
    {position: 123, name: 'card-wellsfargo.svg', component: CardWellsfargo123},
    {position: 124, name: 'capital-one.svg', component: CapitalOne124},
    {position: 125, name: 'simple-illustration__track-shoe.svg', component: SimpleIllustrationTrackShoe125},
    {position: 126, name: 'telescope.svg', component: Telescope126},
    {position: 127, name: 'simple-illustration__paperairplane.svg', component: SimpleIllustrationPaperairplane127},
    {position: 128, name: 'card-visa-large.svg', component: CardVisaLarge128},
    {position: 129, name: 'netsuite-icon-square.svg', component: NetsuiteIconSquare129},
    {position: 130, name: 'simple-illustration__wallet-alt.svg', component: SimpleIllustrationWalletAlt130},
    {position: 131, name: 'simple-illustration__bill.svg', component: SimpleIllustrationBill131},
    {position: 132, name: 'simple-illustration__smartscan.svg', component: SimpleIllustrationSmartscan132},
    {position: 133, name: 'charles-schwab.svg', component: CharlesSchwab133},
    {position: 134, name: 'card-wellsfargo-large.svg', component: CardWellsfargoLarge134},
    {position: 135, name: 'simple-illustration__pencil.svg', component: SimpleIllustrationPencil135},
    {position: 136, name: 'tada--yellow.svg', component: TadaYellow136},
    {position: 137, name: 'simple-illustration__concierge-bubble.svg', component: SimpleIllustrationConciergeBubble137},
    {position: 138, name: 'tada--blue.svg', component: TadaBlue138},
    {position: 139, name: 'todd-behind-cloud.svg', component: ToddBehindCloud139},
    {position: 140, name: 'simple-illustration__invoice.svg', component: SimpleIllustrationInvoice140},
    {position: 141, name: 'simple-illustration__approval.svg', component: SimpleIllustrationApproval141},
    {position: 142, name: 'netsuite-oracle-icon.svg', component: NetsuiteOracleIcon142},
    {position: 143, name: 'simple-illustration__sendmoney.svg', component: SimpleIllustrationSendmoney143},
    {position: 144, name: 'simple-illustration__hourglass.svg', component: SimpleIllustrationHourglass144},
    {position: 145, name: 'simple-illustration__treasurechest.svg', component: SimpleIllustrationTreasurechest145},
    {position: 146, name: 'discover.svg', component: Discover146},
    {position: 147, name: 'simple-illustration__moneybadge.svg', component: SimpleIllustrationMoneybadge147},
    {position: 148, name: 'simple-illustration__car-ice.svg', component: SimpleIllustrationCarIce148},
    {position: 149, name: 'simple-illustration__car.svg', component: SimpleIllustrationCar149},
    {position: 150, name: 'simple-illustration__concierge.svg', component: SimpleIllustrationConcierge150},
    {position: 151, name: 'simple-illustration__shield.svg', component: SimpleIllustrationShield151},
    {position: 152, name: 'simple-illustration__car_pink.svg', component: SimpleIllustrationCarPink152},
    {position: 153, name: 'capital-one.svg', component: CapitalOne153},
    {position: 154, name: 'simple-illustration__credit-cards.svg', component: SimpleIllustrationCreditCards154},
    {position: 155, name: 'simple-illustration__coins.svg', component: SimpleIllustrationCoins155},
    {position: 156, name: 'receipts-search--yellow.svg', component: ReceiptsSearchYellow156},
    {position: 157, name: 'citizens.svg', component: Citizens157},
    {position: 158, name: 'discover.svg', component: Discover158},
    {position: 159, name: 'simple-illustration__mailbox.svg', component: SimpleIllustrationMailbox159},
    {position: 160, name: 'simple-illustration__headset.svg', component: SimpleIllustrationHeadset160},
    {position: 161, name: 'bank-mouse--green.svg', component: BankMouseGreen161},
    {position: 162, name: 'simple-illustration__splitbill.svg', component: SimpleIllustrationSplitbill162},
    {position: 163, name: 'simple-illustration__binoculars.svg', component: SimpleIllustrationBinoculars163},
    {position: 164, name: 'bank-user--green.svg', component: BankUserGreen164},
    {position: 165, name: 'simple-illustration__sanfrancisco.svg', component: SimpleIllustrationSanfrancisco165},
    {position: 166, name: 'simple-illustration__lockclosed.svg', component: SimpleIllustrationLockclosed166},
    {position: 167, name: 'simple-illustration__lockopen.svg', component: SimpleIllustrationLockopen167},
    {position: 168, name: 'simple-illustration__smartscan.svg', component: SimpleIllustrationSmartscan168},
    {position: 169, name: 'simple-illustration__mobileapp.svg', component: SimpleIllustrationMobileapp169},
    {position: 170, name: 'empty-state__attach-receipt.svg', component: EmptyStateAttachReceipt170},
    {position: 171, name: 'simple-illustration__creditcards--green.svg', component: SimpleIllustrationCreditcardsGreen171},
    {position: 172, name: 'simple-illustration__teachers-unite.svg', component: SimpleIllustrationTeachersUnite172},
    {position: 173, name: 'simple-illustration__trashcan.svg', component: SimpleIllustrationTrashcan173},
    {position: 174, name: 'regions-bank.svg', component: RegionsBank174},
    {position: 175, name: 'simple-illustration__virtualcard.svg', component: SimpleIllustrationVirtualcard175},
    {position: 176, name: 'card-wells_fargo.svg', component: CardWellsFargo176},
    {position: 177, name: 'simple-illustration__creditcardeyes.svg', component: SimpleIllustrationCreditcardeyes177},
    {position: 178, name: 'bank-arrow--pink.svg', component: BankArrowPink178},
    {position: 179, name: 'simple-illustration__luggage.svg', component: SimpleIllustrationLuggage179},
    {position: 180, name: 'jewel-box--yellow.svg', component: JewelBoxYellow180},
    {position: 181, name: 'jewel-box--pink.svg', component: JewelBoxPink181},
    {position: 182, name: 'jewel-box--green.svg', component: JewelBoxGreen182},
    {position: 183, name: 'jewel-box--blue.svg', component: JewelBoxBlue183},
    {position: 184, name: 'expensify-logo--adhoc.svg', component: ExpensifyLogoAdhoc184},
    {position: 185, name: 'card-stripe.svg', component: CardStripe185},
    {position: 186, name: 'simple-illustration__alert.svg', component: SimpleIllustrationAlert186},
    {position: 187, name: 'simple-illustration__coffeemug.svg', component: SimpleIllustrationCoffeemug187},
    {position: 188, name: 'expensify-logo--staging.svg', component: ExpensifyLogoStaging188},
    {position: 189, name: 'usaa.svg', component: Usaa189},
    {position: 190, name: 'citizens-bank.svg', component: CitizensBank190},
    {position: 191, name: 'simple-illustration__palmtree.svg', component: SimpleIllustrationPalmtree191},
    {position: 192, name: 'simple-illustration__house.svg', component: SimpleIllustrationHouse192},
    {position: 193, name: 'simple-illustration__flash.svg', component: SimpleIllustrationFlash193},
    {position: 194, name: 'oracle-icon.svg', component: OracleIcon194},
    {position: 195, name: 'simple-illustration__handcard.svg', component: SimpleIllustrationHandcard195},
    {position: 196, name: 'simple-illustration__magnifyingglass-money.svg', component: SimpleIllustrationMagnifyingglassMoney196},
    {position: 197, name: 'simple-illustration__abacus.svg', component: SimpleIllustrationAbacus197},
    {position: 198, name: 'netsuite-icon.svg', component: NetsuiteIcon198},
    {position: 199, name: 'card-stripe-large.svg', component: CardStripeLarge199},
    {position: 200, name: 'simple-illustration__stopwatch.svg', component: SimpleIllustrationStopwatch200},
    {position: 201, name: 'expensify-logo--dev.svg', component: ExpensifyLogoDev201},
    {position: 202, name: 'xero-icon-circle.svg', component: XeroIconCircle202},
    {position: 203, name: 'xero-icon-square.svg', component: XeroIconSquare203},
    {position: 204, name: 'regions-bank.svg', component: RegionsBank204},
    {position: 205, name: 'simple-illustration__tire.svg', component: SimpleIllustrationTire205},
    {position: 206, name: 'receipt-body.svg', component: ReceiptBody206},
    {position: 207, name: 'simple-illustration__lockclosed_orange.svg', component: SimpleIllustrationLockclosedOrange207},
    {position: 208, name: 'amex.svg', component: Amex208},
    {position: 209, name: 'card-citi.svg', component: CardCiti209},
    {position: 210, name: 'card-amex.svg', component: CardAmex210},
    {position: 211, name: 'xero-icon.svg', component: XeroIcon211},
    {position: 212, name: 'bb-t.svg', component: BbT212},
    {position: 213, name: 'simple-illustration__company-card.svg', component: SimpleIllustrationCompanyCard213},
    {position: 214, name: 'us-bank.svg', component: UsBank214},
    {position: 215, name: 'simple-illustration__email-address.svg', component: SimpleIllustrationEmailAddress215},
    {position: 216, name: 'simple-illustration__tag.svg', component: SimpleIllustrationTag216},
    {position: 217, name: 'sage-intacct-icon.svg', component: SageIntacctIcon217},
    {position: 218, name: 'mastercard.svg', component: Mastercard218},
    {position: 219, name: 'usaa.svg', component: Usaa219},
    {position: 220, name: 'simple-illustration__handearth.svg', component: SimpleIllustrationHandearth220},
    {position: 221, name: 'simple-illustration__receipt.svg', component: SimpleIllustrationReceipt221},
    {position: 222, name: 'card-bofa-large.svg', component: CardBofaLarge222},
    {position: 223, name: 'card-citi-large.svg', component: CardCitiLarge223},
    {position: 224, name: 'card-brex.svg', component: CardBrex224},
    {position: 225, name: 'simple-illustration__lightbulb.svg', component: SimpleIllustrationLightbulb225},
    {position: 226, name: 'concierge-avatar.svg', component: ConciergeAvatar226},
    {position: 227, name: 'expensify-footer-logo-vertical.svg', component: ExpensifyFooterLogoVertical227},
    {position: 228, name: 'expensify-footer-logo.svg', component: ExpensifyFooterLogo228},
    {position: 229, name: 'card-amex-large.svg', component: CardAmexLarge229},
    {position: 230, name: 'sage-intacct-icon-square.svg', component: SageIntacctIconSquare230},
    {position: 231, name: 'money-mouse--pink.svg', component: MoneyMousePink231},
    {position: 232, name: 'MCC-RentalCar.svg', component: MccRentalcar232},
    {position: 233, name: 'car-with-key.svg', component: CarWithKey233},
    {position: 234, name: 'card-mastercard.svg', component: CardMastercard234},
    {position: 235, name: 'simple-illustration__twocards-horizontal.svg', component: SimpleIllustrationTwocardsHorizontal235},
    {position: 236, name: 'new-expensify-adhoc.svg', component: NewExpensifyAdhoc236},
    {position: 237, name: 'card-bofa.svg', component: CardBofa237},
    {position: 238, name: 'money-envelope--blue.svg', component: MoneyEnvelopeBlue238},
    {position: 239, name: 'expensify_wordmark_white.svg', component: ExpensifyWordmarkWhite239},
    {position: 240, name: 'expensify-logo--prod.svg', component: ExpensifyLogoProd240},
    {position: 241, name: 'credit-cards--blue.svg', component: CreditCardsBlue241},
    {position: 242, name: 'generic-dark-large.svg', component: GenericDarkLarge242},
    {position: 243, name: 'generic-light-large.svg', component: GenericLightLarge243},
    {position: 244, name: 'new-expensify-stg.svg', component: NewExpensifyStg244},
    {position: 245, name: 'us-bank.svg', component: UsBank245},
    {position: 246, name: 'bb-t.svg', component: BbT246},
    {position: 247, name: 'oracle-icon-square.svg', component: OracleIconSquare247},
    {position: 248, name: 'card-brex-large.svg', component: CardBrexLarge248},
    {position: 249, name: 'card-capital_one-large.svg', component: CardCapitalOneLarge249},
    {position: 250, name: 'card-plaid-large.svg', component: CardPlaidLarge250},
    {position: 251, name: 'card-chase.svg', component: CardChase251},
    {position: 252, name: 'arrow-split.svg', component: ArrowSplit252},
    {position: 253, name: 'expensify-wordmark.svg', component: ExpensifyWordmark253},
    {position: 254, name: 'gps-track--orange.svg', component: GpsTrackOrange254},
    {position: 255, name: 'card-mastercard-large.svg', component: CardMastercardLarge255},
    {position: 256, name: 'keyboard.svg', component: Keyboard256},
    {position: 257, name: 'simple-illustration__folder-open.svg', component: SimpleIllustrationFolderOpen257},
    {position: 258, name: 'card-capital_one.svg', component: CardCapitalOne258},
    {position: 259, name: 'document-merge.svg', component: DocumentMerge259},
    {position: 260, name: 'simple-illustration__subscription-ppu.svg', component: SimpleIllustrationSubscriptionPpu260},
    {position: 261, name: 'card-capitalone.svg', component: CardCapitalone261},
    {position: 262, name: 'card-plaid.svg', component: CardPlaid262},
    {position: 263, name: 'simple-illustration__chatbubbles.svg', component: SimpleIllustrationChatbubbles263},
    {position: 264, name: 'coins.svg', component: Coins264},
    {position: 265, name: 'card-chase-large.svg', component: CardChaseLarge265},
    {position: 266, name: 'social-instagram.svg', component: SocialInstagram266},
    {position: 267, name: 'volume-high.svg', component: VolumeHigh267},
    {position: 268, name: 'generic-light.svg', component: GenericLight268},
    {position: 269, name: 'generic-dark.svg', component: GenericDark269},
    {position: 270, name: 'simple-illustration__commentbubbles.svg', component: SimpleIllustrationCommentbubbles270},
    {position: 271, name: 'sap-icon.svg', component: SapIcon271},
    {position: 272, name: 'generic-csv-light-large.svg', component: GenericCsvLightLarge272},
    {position: 273, name: 'generic-csv-dark-large.svg', component: GenericCsvDarkLarge273},
    {position: 274, name: 'microsoft-dynamics-icon.svg', component: MicrosoftDynamicsIcon274},
    {position: 275, name: 'simple-illustration__commentbubbles_blue.svg', component: SimpleIllustrationCommentbubblesBlue275},
    {position: 276, name: 'expensify-logo-new.svg', component: ExpensifyLogoNew276},
    {position: 277, name: 'MCC-Taxi.svg', component: MccTaxi277},
    {position: 278, name: 'invoice--orange.svg', component: InvoiceOrange278},
    {position: 279, name: 'simple-illustration__checkmarkcircle.svg', component: SimpleIllustrationCheckmarkcircle279},
    {position: 280, name: 'american-express.svg', component: AmericanExpress280},
    {position: 281, name: 'new-expensify.svg', component: NewExpensify281},
    {position: 282, name: 'simple-illustration__receiptupload.svg', component: SimpleIllustrationReceiptupload282},
    {position: 283, name: 'simple-illustration__buildings.svg', component: SimpleIllustrationBuildings283},
    {position: 284, name: 'simple-illustration__rules.svg', component: SimpleIllustrationRules284},
    {position: 285, name: 'new-expensify-dev.svg', component: NewExpensifyDev285},
    {position: 286, name: 'notifications-avatar.svg', component: NotificationsAvatar286},
    {position: 287, name: 'credit-card-hourglass.svg', component: CreditCardHourglass287},
    {position: 288, name: 'MCC-Groceries.svg', component: MccGroceries288},
    {position: 289, name: 'concierge--exclamation.svg', component: ConciergeExclamation289},
    {position: 290, name: 'add-reaction.svg', component: AddReaction290},
    {position: 291, name: 'microsoft-dynamics-icon-square.svg', component: MicrosoftDynamicsIconSquare291},
    {position: 292, name: 'gear.svg', component: Gear292},
    {position: 293, name: 'train.svg', component: Train293},
    {position: 294, name: 'bank-of-america.svg', component: BankOfAmerica294},
    {position: 295, name: 'new-workspace.svg', component: NewWorkspace295},
    {position: 296, name: 'fidelity.svg', component: Fidelity296},
    {position: 297, name: 'citibank.svg', component: Citibank297},
    {position: 298, name: 'MCC-Commuter.svg', component: MccCommuter298},
    {position: 299, name: 'eReceiptIcon.svg', component: Ereceipticon299},
    {position: 300, name: 'generic-csv-light.svg', component: GenericCsvLight300},
    {position: 301, name: 'generic-csv-dark.svg', component: GenericCsvDark301},
    {position: 302, name: 'receipt-multiple.svg', component: ReceiptMultiple302},
    {position: 303, name: 'MCC-Meals.svg', component: MccMeals303},
    {position: 304, name: 'MCC-Utilities.svg', component: MccUtilities304},
    {position: 305, name: 'emptystate__routepending.svg', component: EmptystateRoutepending305},
    {position: 306, name: 'add-emoji.svg', component: AddEmoji306},
    {position: 307, name: 'american-express.svg', component: AmericanExpress307},
    {position: 308, name: 'google-logo.svg', component: GoogleLogo308},
    {position: 309, name: 'hashtag.svg', component: Hashtag309},
    {position: 310, name: 'expensify-app-icon.svg', component: ExpensifyAppIcon310},
    {position: 311, name: 'receipt-scan.svg', component: ReceiptScan311},
    {position: 312, name: 'filters.svg', component: Filters312},
    {position: 313, name: 'social-podcast.svg', component: SocialPodcast313},
    {position: 314, name: 'wrench.svg', component: Wrench314},
    {position: 315, name: 'workflows.svg', component: Workflows315},
    {position: 316, name: 'new-expensify-dark.svg', component: NewExpensifyDark316},
    {position: 317, name: 'receipt--yellow.svg', component: ReceiptYellow317},
    {position: 318, name: 'thread.svg', component: Thread318},
    {position: 319, name: 'default-avatar_9.svg', component: DefaultAvatar9319},
    {position: 320, name: 'default-avatar_7.svg', component: DefaultAvatar7320},
    {position: 321, name: 'default-avatar_8.svg', component: DefaultAvatar8321},
    {position: 322, name: 'default-avatar_6.svg', component: DefaultAvatar6322},
    {position: 323, name: 'default-avatar_5.svg', component: DefaultAvatar5323},
    {position: 324, name: 'default-avatar_3.svg', component: DefaultAvatar3324},
    {position: 325, name: 'default-avatar_4.svg', component: DefaultAvatar4325},
    {position: 326, name: 'default-avatar_2.svg', component: DefaultAvatar2326},
    {position: 327, name: 'default-avatar_17.svg', component: DefaultAvatar17327},
    {position: 328, name: 'default-avatar_16.svg', component: DefaultAvatar16328},
    {position: 329, name: 'default-avatar_14.svg', component: DefaultAvatar14329},
    {position: 330, name: 'default-avatar_13.svg', component: DefaultAvatar13330},
    {position: 331, name: 'default-avatar_12.svg', component: DefaultAvatar12331},
    {position: 332, name: 'default-avatar_11.svg', component: DefaultAvatar11332},
    {position: 333, name: 'default-avatar_10.svg', component: DefaultAvatar10333},
    {position: 334, name: 'default-avatar_18.svg', component: DefaultAvatar18334},
    {position: 335, name: 'default-avatar_1.svg', component: DefaultAvatar1335},
    {position: 336, name: 'default-avatar_15.svg', component: DefaultAvatar15336},
    {position: 337, name: 'qbo-icon.svg', component: QboIcon337},
    {position: 338, name: 'huntington-bank.svg', component: HuntingtonBank338},
    {position: 339, name: 'bank-of-america.svg', component: BankOfAmerica339},
    {position: 340, name: 'receipt.svg', component: Receipt340},
    {position: 341, name: 'fullscreen.svg', component: Fullscreen341},
    {position: 342, name: 'apple-logo.svg', component: AppleLogo342},
    {position: 343, name: 'citibank.svg', component: Citibank343},
    {position: 344, name: 'receipt-search.svg', component: ReceiptSearch344},
    {position: 345, name: 'sap-icon-square.svg', component: SapIconSquare345},
    {position: 346, name: 'car.svg', component: Car346},
    {position: 347, name: 'car.svg', component: Car347},
    {position: 348, name: 'fidelity.svg', component: Fidelity348},
    {position: 349, name: 'drag-and-drop.svg', component: DragAndDrop349},
    {position: 350, name: 'bug.svg', component: Bug350},
    {position: 351, name: 'crosshair.svg', component: Crosshair351},
    {position: 352, name: 'buildings.svg', component: Buildings352},
    {position: 353, name: 'admin-room.svg', component: AdminRoom353},
    {position: 354, name: 'meter.svg', component: Meter354},
    {position: 355, name: 'simple-illustration__profile.svg', component: SimpleIllustrationProfile355},
    {position: 356, name: 'pnc.svg', component: Pnc356},
    {position: 357, name: 'domain-room.svg', component: DomainRoom357},
    {position: 358, name: 'bellSlash.svg', component: Bellslash358},
    {position: 359, name: 'binoculars.svg', component: Binoculars359},
    {position: 360, name: 'mute.svg', component: Mute360},
    {position: 361, name: 'money-hourglass.svg', component: MoneyHourglass361},
    {position: 362, name: 'receipt-slash.svg', component: ReceiptSlash362},
    {position: 363, name: 'default-avatar_x.svg', component: DefaultAvatarX363},
    {position: 364, name: 'announce-room.svg', component: AnnounceRoom364},
    {position: 365, name: 'concierge--blue.svg', component: ConciergeBlue365},
    {position: 366, name: 'image-crop-square-mask.svg', component: ImageCropSquareMask366},
    {position: 367, name: 'default-avatar_w.svg', component: DefaultAvatarW367},
    {position: 368, name: 'MCC-Gas.svg', component: MccGas368},
    {position: 369, name: 'volume-low.svg', component: VolumeLow369},
    {position: 370, name: 'receipt-plus.svg', component: ReceiptPlus370},
    {position: 371, name: 'huntington-bank.svg', component: HuntingtonBank371},
    {position: 372, name: 'simple-illustration__building.svg', component: SimpleIllustrationBuilding372},
    {position: 373, name: 'comment-bubbles.svg', component: CommentBubbles373},
    {position: 374, name: 'user-lock.svg', component: UserLock374},
    {position: 375, name: 'invoice-generic.svg', component: InvoiceGeneric375},
    {position: 376, name: 'paycheck.svg', component: Paycheck376},
    {position: 377, name: 'default-avatar_h.svg', component: DefaultAvatarH377},
    {position: 378, name: 'task.svg', component: Task378},
    {position: 379, name: 'simple-illustration__receipt-envelope.svg', component: SimpleIllustrationReceiptEnvelope379},
    {position: 380, name: 'default-avatar_m.svg', component: DefaultAvatarM380},
    {position: 381, name: 'link-copy.svg', component: LinkCopy381},
    {position: 382, name: 'default-avatar_e.svg', component: DefaultAvatarE382},
    {position: 383, name: 'filter.svg', component: Filter383},
    {position: 384, name: 'android.svg', component: Android384},
    {position: 385, name: 'image-crop-circle-mask.svg', component: ImageCropCircleMask385},
    {position: 386, name: 'video-slash.svg', component: VideoSlash386},
    {position: 387, name: 'MCC-Misc.svg', component: MccMisc387},
    {position: 388, name: 'credit-card-exclamation.svg', component: CreditCardExclamation388},
    {position: 389, name: 'default-avatar_k.svg', component: DefaultAvatarK389},
    {position: 390, name: 'expensify.svg', component: Expensify390},
    {position: 391, name: 'suitcase.svg', component: Suitcase391},
    {position: 392, name: 'user-eye.svg', component: UserEye392},
    {position: 393, name: 'document-plus.svg', component: DocumentPlus393},
    {position: 394, name: 'default-avatar_r.svg', component: DefaultAvatarR394},
    {position: 395, name: 'fallback-workspace-avatar.svg', component: FallbackWorkspaceAvatar395},
    {position: 396, name: 'make-admin.svg', component: MakeAdmin396},
    {position: 397, name: 'default-avatar_a.svg', component: DefaultAvatarA397},
    {position: 398, name: 'globe.svg', component: Globe398},
    {position: 399, name: 'generic-bank-account.svg', component: GenericBankAccount399},
    {position: 400, name: 'default-avatar_b.svg', component: DefaultAvatarB400},
    {position: 401, name: 'shield.svg', component: Shield401},
    {position: 402, name: 'simple-illustration__report-receipt.svg', component: SimpleIllustrationReportReceipt402},
    {position: 403, name: 'pnc.svg', component: Pnc403},
    {position: 404, name: 'money-search.svg', component: MoneySearch404},
    {position: 405, name: 'workspace-default-avatar.svg', component: WorkspaceDefaultAvatar405},
    {position: 406, name: 'treasure-chest.svg', component: TreasureChest406},
    {position: 407, name: 'eye-disabled.svg', component: EyeDisabled407},
    {position: 408, name: 'deleted-room.svg', component: DeletedRoom408},
    {position: 409, name: 'default-avatar_n.svg', component: DefaultAvatarN409},
    {position: 410, name: 'exit.svg', component: Exit410},
    {position: 411, name: 'MCC-Hotel.svg', component: MccHotel411},
    {position: 412, name: 'stopwatch.svg', component: Stopwatch412},
    {position: 413, name: 'default-avatar_f.svg', component: DefaultAvatarF413},
    {position: 414, name: 'MCC-Services.svg', component: MccServices414},
    {position: 415, name: 'default-avatar_y.svg', component: DefaultAvatarY415},
    {position: 416, name: 'room.svg', component: Room416},
    {position: 417, name: 'all.svg', component: All417},
    {position: 418, name: 'apple.svg', component: Apple418},
    {position: 419, name: 'thumbs-up.svg', component: ThumbsUp419},
    {position: 420, name: 'user-check.svg', component: UserCheck420},
    {position: 421, name: 'default-avatar_s.svg', component: DefaultAvatarS421},
    {position: 422, name: 'hourglass.svg', component: Hourglass422},
    {position: 423, name: 'default-avatar_z.svg', component: DefaultAvatarZ423},
    {position: 424, name: 'money-circle.svg', component: MoneyCircle424},
    {position: 425, name: 'qbo-icon-circle.svg', component: QboIconCircle425},
    {position: 426, name: 'megaphone.svg', component: Megaphone426},
    {position: 427, name: 'luggage.svg', component: Luggage427},
    {position: 428, name: 'qbo-icon-square.svg', component: QboIconSquare428},
    {position: 429, name: 'qbd-icon-square.svg', component: QbdIconSquare429},
    {position: 430, name: 'connect.svg', component: Connect430},
    {position: 431, name: 'arrow-collapse.svg', component: ArrowCollapse431},
    {position: 432, name: 'bed.svg', component: Bed432},
    {position: 433, name: 'scan.svg', component: Scan433},
    {position: 434, name: 'MCC-Airlines.svg', component: MccAirlines434},
    {position: 435, name: 'rotate-image.svg', component: RotateImage435},
    {position: 436, name: 'qrcode.svg', component: Qrcode436},
    {position: 437, name: 'chatbubbles.svg', component: Chatbubbles437},
    {position: 438, name: 'default-avatar_t.svg', component: DefaultAvatarT438},
    {position: 439, name: 'default-avatar_2.svg', component: DefaultAvatar2439},
    {position: 440, name: 'default-avatar_building.svg', component: DefaultAvatarBuilding440},
    {position: 441, name: 'simple-illustration__qr-code.svg', component: SimpleIllustrationQrCode441},
    {position: 442, name: 'multi-tag.svg', component: MultiTag442},
    {position: 443, name: 'concierge.svg', component: Concierge443},
    {position: 444, name: 'default-avatar_p.svg', component: DefaultAvatarP444},
    {position: 445, name: 'default-avatar_3.svg', component: DefaultAvatar3445},
    {position: 446, name: 'chatbubble-reply.svg', component: ChatbubbleReply446},
    {position: 447, name: 'flag_level_03.svg', component: FlagLevel03447},
    {position: 448, name: 'flag_level_02.svg', component: FlagLevel02448},
    {position: 449, name: 'flag_level_01.svg', component: FlagLevel01449},
    {position: 450, name: 'sync.svg', component: Sync450},
    {position: 451, name: 'chatbubble-add.svg', component: ChatbubbleAdd451},
    {position: 452, name: 'eye.svg', component: Eye452},
    {position: 453, name: 'default-avatar_g.svg', component: DefaultAvatarG453},
    {position: 454, name: 'document-slash.svg', component: DocumentSlash454},
    {position: 455, name: 'building.svg', component: Building455},
    {position: 456, name: 'calendar.svg', component: Calendar456},
    {position: 457, name: 'calendar.svg', component: Calendar457},
    {position: 458, name: 'zoom.svg', component: Zoom458},
    {position: 459, name: 'default-avatar_d.svg', component: DefaultAvatarD459},
    {position: 460, name: 'default-avatar_q.svg', component: DefaultAvatarQ460},
    {position: 461, name: 'gallery-not-found.svg', component: GalleryNotFound461},
    {position: 462, name: 'attachment-not-found.svg', component: AttachmentNotFound462},
    {position: 463, name: 'x-circle.svg', component: XCircle463},
    {position: 464, name: 'arrow-up-long.svg', component: ArrowUpLong464},
    {position: 465, name: 'link.svg', component: Link465},
    {position: 466, name: 'printer.svg', component: Printer466},
    {position: 467, name: 'default-avatar_c.svg', component: DefaultAvatarC467},
    {position: 468, name: 'default-avatar_v.svg', component: DefaultAvatarV468},
    {position: 469, name: 'default-avatar_l.svg', component: DefaultAvatarL469},
    {position: 470, name: 'chase.svg', component: Chase470},
    {position: 471, name: 'closed-sign.svg', component: ClosedSign471},
    {position: 472, name: 'arrow-down-long.svg', component: ArrowDownLong472},
    {position: 473, name: 'bank.svg', component: Bank473},
    {position: 474, name: 'light-bulb.svg', component: LightBulb474},
    {position: 475, name: 'tag.svg', component: Tag475},
    {position: 476, name: 'bell.svg', component: Bell476},
    {position: 477, name: 'default-avatar_8.svg', component: DefaultAvatar8477},
    {position: 478, name: 'paypal.svg', component: Paypal478},
    {position: 479, name: 'chase.svg', component: Chase479},
    {position: 480, name: 'chatbubble-unread.svg', component: ChatbubbleUnread480},
    {position: 481, name: 'plane.svg', component: Plane481},
    {position: 482, name: 'default-avatar_u.svg', component: DefaultAvatarU482},
    {position: 483, name: 'monitor.svg', component: Monitor483},
    {position: 484, name: 'question-mark-circle.svg', component: QuestionMarkCircle484},
    {position: 485, name: 'MCC-Mail.svg', component: MccMail485},
    {position: 486, name: 'default-avatar_9.svg', component: DefaultAvatar9486},
    {position: 487, name: 'arrow-circle-clockwise.svg', component: ArrowCircleClockwise487},
    {position: 488, name: 'default-avatar_5.svg', component: DefaultAvatar5488},
    {position: 489, name: 'history.svg', component: History489},
    {position: 490, name: 'trashcan.svg', component: Trashcan490},
    {position: 491, name: 'social-youtube.svg', component: SocialYoutube491},
    {position: 492, name: 'default-avatar_6.svg', component: DefaultAvatar6492},
    {position: 493, name: 'circular-arrow-backwards.svg', component: CircularArrowBackwards493},
    {position: 494, name: 'offline.svg', component: Offline494},
    {position: 495, name: 'rotate.svg', component: Rotate495},
    {position: 496, name: 'gallery.svg', component: Gallery496},
    {position: 497, name: 'new-window.svg', component: NewWindow497},
    {position: 498, name: 'money-bag.svg', component: MoneyBag498},
    {position: 499, name: 'pin.svg', component: Pin499},
    {position: 500, name: 'map.svg', component: Map500},
    {position: 501, name: 'transfer.svg', component: Transfer501},
    {position: 502, name: 'users.svg', component: Users502},
    {position: 503, name: 'arrows-updown.svg', component: ArrowsUpdown503},
    {position: 504, name: 'default-avatar_7.svg', component: DefaultAvatar7504},
    {position: 505, name: 'paperclip.svg', component: Paperclip505},
    {position: 506, name: 'bolt-slash.svg', component: BoltSlash506},
    {position: 507, name: 'default-avatar_1.svg', component: DefaultAvatar1507},
    {position: 508, name: 'user-plus.svg', component: UserPlus508},
    {position: 509, name: 'feed.svg', component: Feed509},
    {position: 510, name: 'td-bank.svg', component: TdBank510},
    {position: 511, name: 'default-avatar_j.svg', component: DefaultAvatarJ511},
    {position: 512, name: 'peace-sign.svg', component: PeaceSign512},
    {position: 513, name: 'info.svg', component: Info513},
    {position: 514, name: 'home-fade-gradient.svg', component: HomeFadeGradient514},
    {position: 515, name: 'home-fade-gradient--mobile.svg', component: HomeFadeGradientMobile515},
    {position: 516, name: 'social-twitter.svg', component: SocialTwitter516},
    {position: 517, name: 'Star.svg', component: Star517},
    {position: 518, name: 'chair.svg', component: Chair518},
    {position: 519, name: 'download.svg', component: Download519},
    {position: 520, name: 'caret-up-down.svg', component: CaretUpDown520},
    {position: 521, name: 'invoice.svg', component: Invoice521},
    {position: 522, name: 'bill.svg', component: Bill522},
    {position: 523, name: 'upload-alt.svg', component: UploadAlt523},
    {position: 524, name: 'collapse.svg', component: Collapse524},
    {position: 525, name: 'upload.svg', component: Upload525},
    {position: 526, name: 'checkmark-circle.svg', component: CheckmarkCircle526},
    {position: 527, name: 'key.svg', component: Key527},
    {position: 528, name: 'default-avatar_4.svg', component: DefaultAvatar4528},
    {position: 529, name: 'menu.svg', component: Menu529},
    {position: 530, name: 'emoji.svg', component: Emoji530},
    {position: 531, name: 'camera.svg', component: Camera531},
    {position: 532, name: 'plane.svg', component: Plane532},
    {position: 533, name: 'expand.svg', component: Expand533},
    {position: 534, name: 'default-avatar_i.svg', component: DefaultAvatarI534},
    {position: 535, name: 'export.svg', component: Export535},
    {position: 536, name: 'chatbubble-slash.svg', component: ChatbubbleSlash536},
    {position: 537, name: 'magnifying-glass.svg', component: MagnifyingGlass537},
    {position: 538, name: 'arrows-leftright.svg', component: ArrowsLeftright538},
    {position: 539, name: 'offline-cloud.svg', component: OfflineCloud539},
    {position: 540, name: 'hamburger.svg', component: Hamburger540},
    {position: 541, name: 'three-dots.svg', component: ThreeDots541},
    {position: 542, name: 'td-bank.svg', component: TdBank542},
    {position: 543, name: 'rotate-left.svg', component: RotateLeft543},
    {position: 544, name: 'shutter.svg', component: Shutter544},
    {position: 545, name: 'plant.svg', component: Plant545},
    {position: 546, name: 'pause.svg', component: Pause546},
    {position: 547, name: 'briefcase.svg', component: Briefcase547},
    {position: 548, name: 'wallet.svg', component: Wallet548},
    {position: 549, name: 'chatbubble-counter.svg', component: ChatbubbleCounter549},
    {position: 550, name: 'soccer-ball.svg', component: SoccerBall550},
    {position: 551, name: 'MCC-Goods.svg', component: MccGoods551},
    {position: 552, name: 'remove-members.svg', component: RemoveMembers552},
    {position: 553, name: 'home.svg', component: Home553},
    {position: 554, name: 'receipt-placeholder-plus.svg', component: ReceiptPlaceholderPlus554},
    {position: 555, name: 'dot-indicator-unfilled.svg', component: DotIndicatorUnfilled555},
    {position: 556, name: 'box.svg', component: Box556},
    {position: 557, name: 'inbox.svg', component: Inbox557},
    {position: 558, name: 'phone.svg', component: Phone558},
    {position: 559, name: 'default-avatar_o.svg', component: DefaultAvatarO559},
    {position: 560, name: 'default-avatar_0.svg', component: DefaultAvatar0560},
    {position: 561, name: 'lock.svg', component: Lock561},
    {position: 562, name: 'calendar-solid.svg', component: CalendarSolid562},
    {position: 563, name: 'pencil.svg', component: Pencil563},
    {position: 564, name: 'arrow-right-long.svg', component: ArrowRightLong564},
    {position: 565, name: 'mail.svg', component: Mail565},
    {position: 566, name: 'fallback-avatar.svg', component: FallbackAvatar566},
    {position: 567, name: 'social-linkedin.svg', component: SocialLinkedin567},
    {position: 568, name: 'exclamation.svg', component: Exclamation568},
    {position: 569, name: 'check-circle.svg', component: CheckCircle569},
    {position: 570, name: 'close.svg', component: Close570},
    {position: 571, name: 'check-square.svg', component: CheckSquare571},
    {position: 572, name: 'document.svg', component: Document572},
    {position: 573, name: 'profile.svg', component: Profile573},
    {position: 574, name: 'flag.svg', component: Flag574},
    {position: 575, name: 'flag.svg', component: Flag575},
    {position: 576, name: 'checkmark.svg', component: Checkmark576},
    {position: 577, name: 'location.svg', component: Location577},
    {position: 578, name: 'arrow-up.svg', component: ArrowUp578},
    {position: 579, name: 'down.svg', component: Down579},
    {position: 580, name: 'creditcard.svg', component: Creditcard580},
    {position: 581, name: 'arrow-right.svg', component: ArrowRight581},
    {position: 582, name: 'copy.svg', component: Copy582},
    {position: 583, name: 'checkbox.svg', component: Checkbox583},
    {position: 584, name: 'back-left.svg', component: BackLeft584},
    {position: 585, name: 'chatbubble.svg', component: Chatbubble585},
    {position: 586, name: 'send.svg', component: Send586},
    {position: 587, name: 'cash.svg', component: Cash587},
    {position: 588, name: 'user.svg', component: User588},
    {position: 589, name: 'expensify-card-icon.svg', component: ExpensifyCardIcon589},
    {position: 590, name: 'circle-slash.svg', component: CircleSlash590},
    {position: 591, name: 'heart.svg', component: Heart591},
    {position: 592, name: 'heart.svg', component: Heart592},
    {position: 593, name: 'plus.svg', component: Plus593},
    {position: 594, name: 'drag-handles.svg', component: DragHandles594},
    {position: 595, name: 'unlock.svg', component: Unlock595},
    {position: 596, name: 'bookmark.svg', component: Bookmark596},
    {position: 597, name: 'social-facebook.svg', component: SocialFacebook597},
    {position: 598, name: 'generic-bank-card.svg', component: GenericBankCard598},
    {position: 599, name: 'table.svg', component: Table599},
    {position: 600, name: 'bolt.svg', component: Bolt600},
    {position: 601, name: 'play.svg', component: Play601},
    {position: 602, name: 'empty-square.svg', component: EmptySquare602},
    {position: 603, name: 'minus.svg', component: Minus603},
    {position: 604, name: 'dot-indicator.svg', component: DotIndicator604},
    {position: 605, name: 'folder.svg', component: Folder605},
];

export default svgItems;
