name: Remote Build Android Newdot

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest-xl
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: RNEF Remote Build - Android
        uses: callstackincubator/android@v1
        with:
          variant: developmentDebug
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-bot: false
