name: Remote Build iOS Hybrid

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: macos-15-xlarge
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          submodules: true
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: RNEF Remote Build - iOS
        uses: callstackincubator/ios@4c2dcc0d6b9c35407cf294e17386b65258a3b6af
        env:
          PROJECT_ROOT_PATH: "Mobile-Expensify/"
        with:
          destination: simulator
          scheme: 'Expensify Dev'
          configuration: Debug
          github-token: ${{ github.token }}
          comment-bot: false
